package at.qe.skeleton.services;

import at.qe.skeleton.common.exceptions.BadRequestException;
import at.qe.skeleton.common.exceptions.ConflictException;
import at.qe.skeleton.dtos.*;
import at.qe.skeleton.models.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.stream.Collectors;
import java.util.OptionalDouble;

/*
DISCLAIMER
Method comments were generated by AI with minimal self changes to save time
 */

/**
 * Service responsible for all analytics and data-aggregation operations.
 *
 * <p><b>Role-based access matrix:</b></p>
 * <ul>
 *   <li><b>EMPLOYEE</b> – own office (privacy-mode permitting) + common areas of their department.</li>
 *   <li><b>DEPARTMENT_LEAD</b> – all rooms in their department; office trends at reduced granularity
 *       when the room is above minimum occupancy; common areas at full granularity.</li>
 *   <li><b>MANAGEMENT</b> – aggregated department/company data only; violation breakdowns are
 *       anonymized (no room-level traceability).</li>
 *   <li><b>BUILDING_ADMIN</b> – full access to all measurement data; never sees user-room assignments.</li>
 *   <li><b>SYSTEM_ADMIN</b> – explicitly excluded from every endpoint (no access to climate data).</li>
 * </ul>
 */
@Slf4j
@Service
public class AnalyticsService {

    private final MeasurementService measurementService;
    private final ThresholdViolationService thresholdViolationService;
    private final RoomService roomService;
    private final DepartmentService departmentService;
    private final EmployeeProfileService employeeProfileService;
    private final AuthenticatedUserService authenticatedUserService;

    public AnalyticsService(
            MeasurementService measurementService,
            ThresholdViolationService thresholdViolationService,
            RoomService roomService,
            DepartmentService departmentService,
            EmployeeProfileService employeeProfileService,
            AuthenticatedUserService authenticatedUserService) {
        this.measurementService = measurementService;
        this.thresholdViolationService = thresholdViolationService;
        this.roomService = roomService;
        this.departmentService = departmentService;
        this.employeeProfileService = employeeProfileService;
        this.authenticatedUserService = authenticatedUserService;
    }

    /**
     * Returns a statistical summary (latest, avg, min, max, count) for every metric
     * measured in the requested room over the given time window.
     *
     * <p><b>Access rules:</b></p>
     * <ul>
     *   <li><b>EMPLOYEE</b> – own office only (privacy-mode / minimum-occupancy guard applies);
     *       common areas of their department are always accessible.</li>
     *   <li><b>DEPARTMENT_LEAD</b> – any room that belongs to their department.</li>
     *   <li><b>BUILDING_ADMIN</b> – any room, unrestricted.</li>
     * </ul>
     *
     * <p>When {@code from} / {@code to} are omitted the service defaults to the last 24 hours.</p>
     *
     * @param roomId the ID of the room whose summary is requested
     * @param from   optional window start (inclusive); defaults to {@code to – 24 h}
     * @param to     optional window end (inclusive); defaults to now
     * @return {@link RoomSummaryDTO} containing per-metric statistics
     * @throws AccessDeniedException if the caller lacks read access to the room
     * @throws ConflictException     if {@code from} is after {@code to}
     */
    @PreAuthorize("hasAnyAuthority('EMPLOYEE','DEPARTMENT_LEAD','BUILDING_ADMIN')")
    public RoomSummaryDTO getRoomSummary(Long roomId, LocalDateTime from, LocalDateTime to) {
        Room room = roomService.getById(roomId);
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();

        assertRoomReadAccess(currentUser, room);
        assertOccupancyIfRequired(currentUser, room);

        LocalDateTime effectiveTo = to != null ? to : LocalDateTime.now();
        LocalDateTime effectiveFrom = from != null ? from : effectiveTo.minusHours(24);
        validateRange(effectiveFrom, effectiveTo);

        List<Measurement> measurements = measurementService.getFiltered(roomId, null, effectiveFrom, effectiveTo);

        Map<Metric, MetricSummaryDTO> metricStats = Arrays.stream(Metric.values())
                .collect(Collectors.toMap(m -> m, m -> buildMetricSummary(measurements, m)));

        log.debug("Generated room summary for roomId={}, userId={}", roomId, currentUser.getId());
        return new RoomSummaryDTO(roomId, room.getName(), LocalDateTime.now(), metricStats);
    }

    /**
     * Returns a time-series trend for a single metric in the requested room.
     *
     * <p><b>Granularity rules:</b></p>
     * <ul>
     *   <li><b>EMPLOYEE / BUILDING_ADMIN</b> – automatic bucket selection based on window length
     *       (raw ≤ 7 d, 1 h ≤ 90 d, 6 h ≤ 1 y, 1 d otherwise).</li>
     *   <li><b>DEPARTMENT_LEAD viewing an office room above minimum occupancy</b> – forced reduced
     *       granularity (minimum daily averages) regardless of window length, as required by the
     *       privacy specification.</li>
     *   <li><b>DEPARTMENT_LEAD viewing a common area</b> – full automatic granularity.</li>
     * </ul>
     *
     * <p>When {@code from} / {@code to} are omitted the service defaults to the last 24 hours.</p>
     *
     * @param roomId the ID of the room
     * @param metric the climate metric to retrieve (e.g. TEMPERATURE, CO2)
     * @param from   optional window start; defaults to {@code to – 24 h}
     * @param to     optional window end; defaults to now
     * @return {@link RoomTrendDTO} containing the resolved bucket size and data points
     * @throws AccessDeniedException if the caller lacks read access to the room
     * @throws ConflictException     if {@code from} is after {@code to}
     */
    @PreAuthorize("hasAnyAuthority('EMPLOYEE','DEPARTMENT_LEAD','BUILDING_ADMIN')")
    public RoomTrendDTO getRoomTrend(Long roomId, Metric metric, LocalDateTime from, LocalDateTime to) {
        Room room = roomService.getById(roomId);
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();

        assertRoomReadAccess(currentUser, room);
        assertOccupancyIfRequired(currentUser, room);

        LocalDateTime effectiveTo = to != null ? to : LocalDateTime.now();
        LocalDateTime effectiveFrom = from != null ? from : effectiveTo.minusHours(24);
        validateRange(effectiveFrom, effectiveTo);

        List<Measurement> measurements = measurementService.getFiltered(
                roomId, metric, effectiveFrom, effectiveTo);

        /*
         * DEPARTMENT_LEAD + office room: apply forced reduced granularity only when the room
         * is above minimum occupancy (privacy mode OFF). If privacy mode is ON the room would
         * have already been blocked by assertOccupancyIfRequired for EMPLOYEEs; DEPARTMENT_LEAD
         * is exempt from the hard block but still sees reduced granularity for occupied offices.
         *
         * Common areas are always shown at full granularity for all roles.
         */
        boolean forceReduced = hasRole(currentUser, UserxRole.DEPARTMENT_LEAD)
                && room.getRoomType() == RoomType.OFFICE
                && !Boolean.TRUE.equals(room.getPrivacyMode());

        String bucketSize = forceReduced
                ? forcedReducedBucket(effectiveFrom, effectiveTo)
                : resolveBucketSize(effectiveFrom, effectiveTo);

        List<TrendPointDTO> points = toPoints(measurements, effectiveFrom, effectiveTo, bucketSize);

        log.debug("Generated room trend: roomId={}, metric={}, bucketSize={}, forceReduced={}",
                roomId, metric, bucketSize, forceReduced);
        return new RoomTrendDTO(roomId, metric, bucketSize, forceReduced, points);
    }

    /**
     * Returns a violation summary for a single room broken down by metric.
     *
     * <p><b>Access rules:</b></p>
     * <ul>
     *   <li><b>EMPLOYEE</b> – own office only (occupancy guard applies); common areas of their department.</li>
     *   <li><b>DEPARTMENT_LEAD</b> – any room in their department.</li>
     *   <li><b>BUILDING_ADMIN</b> – any room.</li>
     * </ul>
     *
     * @throws AccessDeniedException if the caller lacks read access to the room
     */
    @PreAuthorize("hasAnyAuthority('EMPLOYEE','DEPARTMENT_LEAD','BUILDING_ADMIN')")
    public RoomViolationSummaryDTO getRoomViolationSummary(Long roomId) {
        Room room = roomService.getById(roomId);
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();

        assertRoomReadAccess(currentUser, room);
        assertOccupancyIfRequired(currentUser, room);

        List<ThresholdViolation> violations = thresholdViolationService.findAll(null, roomId, null);

        int total    = violations.size();
        int active   = (int) violations.stream()
                .filter(v -> v.getViolationStatus() == ViolationStatus.ACTIVE).count();
        int resolved = (int) violations.stream()
                .filter(v -> v.getViolationStatus() == ViolationStatus.RESOLVED).count();

        List<ViolationBreakdownDTO> byMetric = Arrays.stream(Metric.values())
                .map(metric -> new ViolationBreakdownDTO(
                        metric.name(),
                        (int) violations.stream()
                                .filter(v -> v.getMetric() == metric).count()))
                .filter(dto -> dto.count() > 0)
                .toList();

        log.debug("Generated room violation summary: roomId={}, total={}, active={}", roomId, total, active);
        return new RoomViolationSummaryDTO(roomId, room.getName(), total, active, resolved, byMetric);
    }

    /**
     * Returns an aggregated summary for an entire department: active violation count and
     * average metric values across all active rooms in the requested time window.
     *
     * <p><b>Access rules:</b></p>
     * <ul>
     *   <li><b>DEPARTMENT_LEAD</b> – their own department only.</li>
     *   <li><b>MANAGEMENT / BUILDING_ADMIN</b> – any department.</li>
     * </ul>
     *
     * @param departmentId the ID of the department
     * @param from         optional window start; defaults to {@code to – 24 h}
     * @param to           optional window end; defaults to now
     * @return {@link DepartmentAnalyticsDTO} with room count, active violations, windowed avg metrics,
     *         and current (latest-per-room) metric snapshot
     * @throws AccessDeniedException if a DEPARTMENT_LEAD requests another department
     */
    @PreAuthorize("hasAnyAuthority('DEPARTMENT_LEAD','MANAGEMENT','BUILDING_ADMIN')")
    public DepartmentAnalyticsDTO getDepartmentSummary(Long departmentId,
                                                       LocalDateTime from, LocalDateTime to) {
        Department department = departmentService.getDepartmentById(departmentId);
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();

        if (hasRole(currentUser, UserxRole.DEPARTMENT_LEAD) && !isLeaderOf(currentUser, department)) {
            throw new AccessDeniedException("You may only view your own department.");
        }

        List<Room> rooms = department.getRooms().stream()
                .filter(Room::isActive)
                .toList();

        int activeViolations = rooms.stream()
                .mapToInt(r -> thresholdViolationService
                        .findAll(ViolationStatus.ACTIVE, r.getId(), null).size()).sum();

        Map<Metric, Double> avgMetrics = computeAvgMetricsForRooms(rooms, from, to);

        // "momentane Messwerte": latest reading per room averaged across rooms
        // This gives a snapshot of current conditions distinct from the windowed average
        Map<Metric, Double> currentMetrics = computeLatestMetricsForRooms(rooms);

        log.debug("Generated department summary for departmentId={}", departmentId);
        return new DepartmentAnalyticsDTO(departmentId, department.getName(), rooms.size(), activeViolations,
                avgMetrics, currentMetrics);
    }

    /**
     * Returns an aggregated time-series trend for a single metric across all active rooms
     * in a department.
     *
     * <p>Intended for trend-indicator views (improvement / deterioration over weeks / months).
     * Bucket size is selected automatically based on the requested window.</p>
     *
     * <p><b>Access rules:</b></p>
     * <ul>
     *   <li><b>DEPARTMENT_LEAD</b> – their own department only.</li>
     *   <li><b>MANAGEMENT / BUILDING_ADMIN</b> – any department.</li>
     * </ul>
     *
     * <p>Default window when omitted: last 7 days.</p>
     *
     * @param departmentId the ID of the department
     * @param metric       the climate metric to aggregate
     * @param from         optional window start; defaults to {@code to – 7 d}
     * @param to           optional window end; defaults to now
     * @return {@link DepartmentTrendDTO} with bucket size and aggregated data points
     * @throws AccessDeniedException if a DEPARTMENT_LEAD requests another department
     * @throws ConflictException     if {@code from} is after {@code to}
     */
    @PreAuthorize("hasAnyAuthority('DEPARTMENT_LEAD','MANAGEMENT','BUILDING_ADMIN')")
    public DepartmentTrendDTO getDepartmentTrend(Long departmentId,
                                                 Metric metric,
                                                 LocalDateTime from, LocalDateTime to) {
        Department department = departmentService.getDepartmentById(departmentId);
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();

        if (hasRole(currentUser, UserxRole.DEPARTMENT_LEAD) && !isLeaderOf(currentUser, department)) {
            throw new AccessDeniedException("You may only view your own department.");
        }

        LocalDateTime effectiveTo = to != null ? to : LocalDateTime.now();
        LocalDateTime effectiveFrom = from != null ? from : effectiveTo.minusDays(7);
        validateRange(effectiveFrom, effectiveTo);

        List<Room> rooms = department.getRooms().stream()
                .filter(Room::isActive)
                .toList();

        String bucketSize = resolveBucketSize(effectiveFrom, effectiveTo);

        // Build per-room buckets first, then average across rooms per bucket (room-fair).
        Map<Long, List<Measurement>> byRoom = new HashMap<>();
        for (Room r : rooms) {
            byRoom.put(r.getId(),
                    measurementService.getFiltered(r.getId(), metric, effectiveFrom, effectiveTo));
        }
        List<TrendPointDTO> points = toRoomFairPoints(byRoom, effectiveFrom, effectiveTo, bucketSize);

        log.debug("Generated department trend: departmentId={}, metric={}, bucketSize={}",
                departmentId, metric, bucketSize);
        return new DepartmentTrendDTO(metric, bucketSize, points);
    }

    /**
     * Returns a violation summary for a department broken down by metric and (conditionally) by room.
     *
     * <p><b>Anonymization rules:</b></p>
     * <ul>
     *   <li><b>MANAGEMENT</b> – room-level breakdown is omitted; violations are not traceable to
     *       individual rooms, satisfying the anonymization requirement.</li>
     *   <li><b>DEPARTMENT_LEAD / BUILDING_ADMIN</b> – full room-level breakdown included.</li>
     * </ul>
     *
     * <p><b>Access rules:</b></p>
     * <ul>
     *   <li><b>DEPARTMENT_LEAD</b> – their own department only.</li>
     *   <li><b>MANAGEMENT / BUILDING_ADMIN</b> – any department.</li>
     * </ul>
     *
     * @param departmentId the ID of the department
     * @return {@link ViolationSummaryDTO} with total, active, resolved counts and breakdowns
     * @throws AccessDeniedException if a DEPARTMENT_LEAD requests another department
     */
    @PreAuthorize("hasAnyAuthority('DEPARTMENT_LEAD','MANAGEMENT','BUILDING_ADMIN')")
    public ViolationSummaryDTO getDepartmentViolationSummary(Long departmentId) {
        Department department = departmentService.getDepartmentById(departmentId);
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();

        if (hasRole(currentUser, UserxRole.DEPARTMENT_LEAD) && isLeaderOf(currentUser, department)) {
            throw new AccessDeniedException("You may only view your own department.");
        }

        boolean anonymize = hasRole(currentUser, UserxRole.MANAGEMENT);

        List<Room> rooms = department.getRooms().stream()
                .filter(Room::isActive)
                .toList();
        List<Long> roomIds = rooms.stream().map(Room::getId).toList();

        List<ThresholdViolation> violations = thresholdViolationService
                .findAll(null, null, departmentId);

        return buildViolationSummary(violations, roomIds, rooms, anonymize);
    }

    /**
     * Returns a company-wide dashboard aggregating employee count, total active rooms,
     * total active violations, and per-department breakdowns with average metric values.
     *
     * <p>Intended as the top-level entry point for MANAGEMENT trend monitoring and
     * BUILDING_ADMIN operational oversight.</p>
     *
     * <p>Default window when omitted: last 7 days.</p>
     *
     * @param from optional window start for metric averages; defaults to {@code to – 7 d}
     * @param to   optional window end; defaults to now
     * @return {@link CompanyDashboardDTO} with aggregated company-wide data
     * @throws ConflictException if {@code from} is after {@code to}
     */
    @PreAuthorize("hasAnyAuthority('MANAGEMENT','BUILDING_ADMIN')")
    public CompanyDashboardDTO getCompanyDashboard(LocalDateTime from, LocalDateTime to) {
        List<Department> departments = departmentService.getAll();

        LocalDateTime effectiveTo = to != null ? to : LocalDateTime.now();
        LocalDateTime effectiveFrom = from != null ? from : effectiveTo.minusDays(7);
        validateRange(effectiveFrom, effectiveTo);

        int totalEmployees = employeeProfileService.getAll(null, null).size();
        int totalRooms = 0;
        int activeViolations = 0;
        List<DepartmentDashboardDTO> departmentDTOs = new ArrayList<>();

        for (Department dept : departments) {
            List<Room> rooms = dept.getRooms().stream()
                    .filter(Room::isActive)
                    .toList();
            totalRooms += rooms.size();

            int deptActiveViolations = rooms.stream()
                    .mapToInt(r -> thresholdViolationService
                            .findAll(ViolationStatus.ACTIVE, r.getId(), null).size())
                    .sum();
            activeViolations += deptActiveViolations;

            Map<Metric, Double> avgMetrics = computeAvgMetricsForRooms(rooms, effectiveFrom, effectiveTo);
            Map<Metric, Double> currentMetrics = computeLatestMetricsForRooms(rooms);

            departmentDTOs.add(new DepartmentDashboardDTO(
                    dept.getId(), dept.getName(), deptActiveViolations, avgMetrics, currentMetrics));
        }

        log.debug("Generated company dashboard: departments={}, totalRooms={}, activeViolations={}",
                departments.size(), totalRooms, activeViolations);
        return new CompanyDashboardDTO(LocalDateTime.now(), totalRooms, totalEmployees, activeViolations, departmentDTOs);
    }

    /**
     * Returns a company-wide violation summary broken down by metric and (conditionally) by room.
     *
     * <p><b>Anonymization rules:</b></p>
     * <ul>
     *   <li><b>MANAGEMENT</b> – room-level breakdown is omitted so violations remain
     *       non-traceable to individual rooms (anonymization requirement).</li>
     *   <li><b>BUILDING_ADMIN</b> – full room-level breakdown is included.</li>
     * </ul>
     *
     * @return {@link ViolationSummaryDTO} with totals, metric breakdown, and optional room breakdown
     */
    @PreAuthorize("hasAnyAuthority('MANAGEMENT','BUILDING_ADMIN')")
    public ViolationSummaryDTO getCompanyViolationSummary() {
        Userx currentUser = authenticatedUserService.getAuthenticatedUser();
        boolean anonymize = hasRole(currentUser, UserxRole.MANAGEMENT);

        List<ThresholdViolation> violations = thresholdViolationService.findAll(null, null, null);

        List<Room> allRooms = departmentService.getAll().stream()
                .flatMap(d -> d.getRooms().stream())
                .filter(Room::isActive)
                .toList();
        List<Long> roomIds = allRooms.stream().map(Room::getId).toList();

        log.debug("Generated company violation summary: totalViolations={}, anonymize={}", violations.size(), anonymize);
        return buildViolationSummary(violations, roomIds, allRooms, anonymize);
    }

    /**
     * Returns a company-wide time-series trend for a single metric, aggregated across
     * all active rooms in all departments.
     *
     * <p>Designed for MANAGEMENT trend-indicator views (improvement / deterioration over
     * weeks / months at company level) and BUILDING_ADMIN operational analysis.</p>
     *
     * <p>Default window when omitted: last 7 days.</p>
     *
     * @param metric the climate metric to aggregate
     * @param from   optional window start; defaults to {@code to – 7 d}
     * @param to     optional window end; defaults to now
     * @return {@link CompanyTrendDTO} with bucket size and aggregated data points
     * @throws ConflictException if {@code from} is after {@code to}
     */
    @PreAuthorize("hasAnyAuthority('MANAGEMENT','BUILDING_ADMIN')")
    public CompanyTrendDTO getCompanyTrend(Metric metric,
                                           LocalDateTime from, LocalDateTime to) {

        LocalDateTime effectiveTo = to != null ? to : LocalDateTime.now();
        LocalDateTime effectiveFrom = from != null ? from : effectiveTo.minusDays(7);
        validateRange(effectiveFrom, effectiveTo);

        List<Room> allRooms = departmentService.getAll().stream()
                .flatMap(d -> d.getRooms().stream())
                .filter(Room::isActive)
                .toList();

        String bucketSize = resolveBucketSize(effectiveFrom, effectiveTo);

        // Build per-room buckets first, then average across rooms per bucket (room-fair).
        Map<Long, List<Measurement>> byRoom = new HashMap<>();
        for (Room r : allRooms) {
            byRoom.put(r.getId(), measurementService.getFiltered(r.getId(), metric, effectiveFrom, effectiveTo));
        }
        List<TrendPointDTO> points = toRoomFairPoints(byRoom, effectiveFrom, effectiveTo, bucketSize);

        log.debug("Generated company trend: metric={}, bucketSize={}, points={}", metric, bucketSize, points.size());
        return new CompanyTrendDTO(metric, bucketSize, points);
    }

    /**
     * Asserts that the current user may read data from this room.
     *
     * <ul>
     *   <li><b>BUILDING_ADMIN</b> – always allowed.</li>
     *   <li><b>DEPARTMENT_LEAD</b> – room must belong to their department (office or common area).</li>
     *   <li><b>EMPLOYEE</b> – only their own assigned office, or common areas of their department.</li>
     * </ul>
     *
     * @throws AccessDeniedException when access is not permitted
     */
    private void assertRoomReadAccess(Userx user, Room room) {
        if (hasRole(user, UserxRole.BUILDING_ADMIN)) return;

        EmployeeProfile profile = employeeProfileService.getMyProfile().orElse(null);

        if (hasRole(user, UserxRole.DEPARTMENT_LEAD)) {
            if (room.getDepartment() == null || !isLeaderOf(user, room.getDepartment())) {
                throw new AccessDeniedException("Room does not belong to your department.");
            }
            return;
        }

        if (hasRole(user, UserxRole.EMPLOYEE)) {
            if (profile == null) {
                throw new AccessDeniedException("No employee profile found.");
            }

            Department employeeDept = profile.getDepartment();
            boolean isOwnRoom = profile.getRoom() != null && profile.getRoom().getId().equals(room.getId());
            boolean isCommonArea =
                    room.getRoomType() == RoomType.COMMON_AREAS
                            && room.getDepartment() != null
                            && employeeDept != null
                            && room.getDepartment().getId().equals(employeeDept.getId());

            if (!isOwnRoom && !isCommonArea) {
                throw new AccessDeniedException("You may only view your own room or common areas of your department.");
            }
            return;
        }

        throw new AccessDeniedException("Insufficient privileges to access room data.");
    }

    /**
     * Enforces the minimum-occupancy / privacy-mode guard for EMPLOYEE access to office rooms.
     *
     * <p>Common areas bypass this check entirely. DEPARTMENT_LEAD and BUILDING_ADMIN are also
     * exempt — the Department Lead sees reduced granularity for occupied offices instead
     * (handled in {@link #getRoomTrend}).</p>
     *
     * @throws AccessDeniedException when privacy mode is active (minimum occupancy not met)
     */
    private void assertOccupancyIfRequired(Userx user, Room room) {
        if (!hasRole(user, UserxRole.EMPLOYEE)) return;
        if (room.getRoomType() == RoomType.COMMON_AREAS) return;

        if (Boolean.TRUE.equals(room.getPrivacyMode())) {
            throw new AccessDeniedException("Room climate data is not available: minimum occupancy requirement not met.");
        }
    }

    private boolean hasRole(Userx user, UserxRole role) {
        return user.getRoles() != null && user.getRoles().contains(role);
    }

    private boolean isLeaderOf(Userx user, Department department) {
        if (user == null || department == null) return false;

        Userx leader = department.getDepartmentLeader();
        if (leader == null) return false;

        return Objects.equals(leader.getId(), user.getId());
    }

    private MetricSummaryDTO buildMetricSummary(List<Measurement> all, Metric metric) {
        List<Float> values = all.stream()
                .filter(m -> m.getMetric() == metric)
                .sorted(Comparator.comparing(Measurement::getTimestamp))
                .map(Measurement::getMeasurement)
                .toList();

        if (values.isEmpty()) {
            return new MetricSummaryDTO(null, null, null, null, 0L);
        }

        double avg = round2(values.stream().mapToDouble(Float::doubleValue).average().orElse(0));
        double min = round2(values.stream().mapToDouble(Float::doubleValue).min().orElse(0));
        double max = round2(values.stream().mapToDouble(Float::doubleValue).max().orElse(0));
        double latest = round2(values.getLast());

        return new MetricSummaryDTO(latest, avg, min, max, (long) values.size());
    }

    /**
     * Forced reduced bucket for DEPARTMENT_LEAD viewing occupied office rooms.
     * Minimum granularity is daily averages regardless of window length, as required
     * by the privacy specification (§1.5.3 Abteilungsleitung).
     *
     * <p>Bucket mapping:</p>
     * <ul>
     *   <li>≤ 30 days → {@code 1d} (daily averages)</li>
     *   <li>&gt; 30 days → {@code 1w} (weekly averages)</li>
     * </ul>
     */
    private String forcedReducedBucket(LocalDateTime from, LocalDateTime to) {
        long hours = ChronoUnit.HOURS.between(from, to);
        if (hours <= 720) return "1d";
        return "1w";
    }

    /**
     * Automatic bucket resolution based on window length.
     *
     * <ul>
     *   <li>≤ 7 d  → {@code raw} </li>
     *   <li>≤ 90 d → {@code 1h}  </li>
     *   <li>≤ 1 y  → {@code 6h}  </li>
     *   <li>&gt; 1 y → {@code 1d}</li>
     * </ul>
     */
    private String resolveBucketSize(LocalDateTime from, LocalDateTime to) {
        long hours = ChronoUnit.HOURS.between(from, to);
        if (hours <= 168)  return "raw";
        if (hours <= 2160) return "1h";
        if (hours <= 8760) return "6h";
        return "1d";
    }

    /**
     * Builds a room-fair time-series from per-room measurement maps.
     *
     * <p>Algorithm:</p>
     * <ol>
     *   <li>Bucket each room's measurements independently into the same time grid.</li>
     *   <li>For every bucket timestamp, average the per-room bucket averages
     *       (rooms with no data in a bucket are excluded, not counted as zero).</li>
     * </ol>
     *
     * <p>This ensures that rooms with higher sensor frequency or longer uptime do not
     * dominate the cross-room aggregate — each room contributes equally per bucket.</p>
     *
     * @param byRoom     measurements per room ID
     * @param from       effective window start
     * @param to         effective window end
     * @param bucketSize resolved bucket size string (e.g. {@code "1h"}, {@code "1d"})
     * @return room-fair trend points sorted by timestamp
     */
    private List<TrendPointDTO> toRoomFairPoints(Map<Long, List<Measurement>> byRoom,
                                                 LocalDateTime from,
                                                 LocalDateTime to,
                                                 String bucketSize) {
        if (byRoom.isEmpty()) return Collections.emptyList();

        // For "raw" bucket in a multi room context we still bucket by 1m slots
        // so that cross-room averaging is meaningful, raw is only meaningful for single rooms.
        String effectiveBucket = "raw".equals(bucketSize) ? "raw" : bucketSize;

        if ("raw".equals(effectiveBucket)) {
            // Flat merge and sort: only reached for single room callers; multi-room callers
            // always get a non raw bucket from resolveBucketSize via getDepartmentTrend /
            // getCompanyTrend (those default to >= 7-day windows).
            List<Measurement> all = byRoom.values().stream()
                    .flatMap(Collection::stream)
                    .sorted(Comparator.comparing(Measurement::getTimestamp))
                    .toList();
            return all.stream()
                    .map(m -> new TrendPointDTO(m.getTimestamp(), round2(m.getMeasurement())))
                    .toList();
        }

        long bucketMinutes = switch (effectiveBucket) {
            case "1d" -> 1440L;
            case "1w" -> 10080L;
            case "6h" -> 360L;
            default   -> 60L;
        };

        // Bucket each room independently: Map<roomId, Map<bucketKey, List<value>>>
        Map<Long, Map<LocalDateTime, Double>> roomBucketAverages = new HashMap<>();

        for (Map.Entry<Long, List<Measurement>> entry : byRoom.entrySet()) {
            Map<LocalDateTime, List<Float>> buckets = new TreeMap<>();

            for (Measurement m : entry.getValue()) {
                LocalDateTime ts = m.getTimestamp();

                if (ts.isBefore(from) || ts.isAfter(to)) continue;

                long idx = ChronoUnit.MINUTES.between(from, ts) / bucketMinutes;
                LocalDateTime key = from.plusMinutes(idx * bucketMinutes);
                buckets.computeIfAbsent(key, k -> new ArrayList<>()).add(m.getMeasurement());
            }
            // Collapse each bucket to its average for this room
            Map<LocalDateTime, Double> roomAvg = new TreeMap<>();
            buckets.forEach((k, vals) -> roomAvg.put(k,
                    vals.stream().mapToDouble(Float::doubleValue).average().orElse(0.0)));
            roomBucketAverages.put(entry.getKey(), roomAvg);
        }

        // Collect all unique bucket timestamps across all rooms
        Set<LocalDateTime> allKeys = roomBucketAverages.values().stream()
                .flatMap(m -> m.keySet().stream())
                .collect(Collectors.toCollection(TreeSet::new));

        // For each timestamp, average the room averages (only rooms that have data)
        return allKeys.stream()
                .map(ts -> {
                    double crossRoomAvg = roomBucketAverages.values().stream()
                            .map(roomAvg -> roomAvg.get(ts))
                            .filter(Objects::nonNull)
                            .mapToDouble(Double::doubleValue)
                            .average()
                            .orElse(0.0);
                    return new TrendPointDTO(ts, round2(crossRoomAvg));
                })
                .toList();
    }

    private List<TrendPointDTO> toPoints(List<Measurement> measurements,
                                         LocalDateTime from, LocalDateTime to,
                                         String bucketSize) {

        if (measurements.isEmpty()) return Collections.emptyList();

        if ("raw".equals(bucketSize)) {
            return measurements.stream()
                    .sorted(Comparator.comparing(Measurement::getTimestamp))
                    .map(m ->
                            new TrendPointDTO(
                                    m.getTimestamp(),
                                    round2(m.getMeasurement()))
                    )
                    .toList();
        }
        return bucketize(measurements, from, to, bucketSize);
    }

    private List<TrendPointDTO> bucketize(List<Measurement> measurements,
                                          LocalDateTime from, LocalDateTime to,
                                          String bucketSize) {
        long bucketMinutes = switch (bucketSize) {
            case "1d" -> 1440L;
            case "1w" -> 10080L;
            case "6h" -> 360L;
            default   -> 60L;
        };

        Map<LocalDateTime, List<Float>> buckets = new TreeMap<>();
        for (Measurement m : measurements) {
            LocalDateTime ts = m.getTimestamp();
            if (ts.isBefore(from) || ts.isAfter(to)) continue;

            long minutesSinceFrom = ChronoUnit.MINUTES.between(from, ts);
            long bucketIndex = minutesSinceFrom / bucketMinutes;
            LocalDateTime key = from.plusMinutes(bucketIndex * bucketMinutes);

            buckets.computeIfAbsent(key, k -> new ArrayList<>()).add(m.getMeasurement());
        }

        return buckets.entrySet().stream()
                .map(e -> new TrendPointDTO(
                        e.getKey(),
                        round2(e.getValue().stream()
                                .mapToDouble(Float::doubleValue)
                                .average()
                                .orElse(0))))
                .toList();
    }

    /**
     * Computes per-metric averages across a list of rooms using a two-level mean:
     * first the average per room, then the average of those room averages.
     *
     * <p>This prevents rooms with higher sensor frequency or longer uptime from dominating
     * the result (flat-merge bias). Each room contributes exactly one value per metric,
     * regardless of how many measurements it produced in the window.</p>
     *
     * <p>Rooms that have no measurements for a given metric in the window are excluded
     * from that metric's average (they contribute no signal, not a zero).</p>
     */
    private Map<Metric, Double> computeAvgMetricsForRooms(List<Room> rooms,
                                                          LocalDateTime from,
                                                          LocalDateTime to) {

        if (rooms.isEmpty()) return Collections.emptyMap();

        LocalDateTime effectiveTo = to != null ? to : LocalDateTime.now();
        LocalDateTime effectiveFrom = from != null ? from : effectiveTo.minusHours(24);

        // Fetch measurements per room up front
        Map<Long, List<Measurement>> byRoom = new HashMap<>();
        for (Room r : rooms) {
            byRoom.put(r.getId(),
                    measurementService.getFiltered(r.getId(), null, effectiveFrom, effectiveTo));
        }

        return Arrays.stream(Metric.values())
                .collect(Collectors.toMap(
                        metric -> metric,
                        metric -> {
                            // Compute the average for this metric inside each room
                            List<Double> roomAverages = byRoom.values().stream()
                                    .map(measurements -> measurements.stream()
                                            .filter(m -> m.getMetric() == metric)
                                            .mapToDouble(Measurement::getMeasurement)
                                            .average())
                                    .filter(OptionalDouble::isPresent)
                                    .map(OptionalDouble::getAsDouble)
                                    .toList();

                            // Average the per-room averages (room-fair mean)
                            return round2(roomAverages.stream()
                                    .mapToDouble(Double::doubleValue)
                                    .average()
                                    .orElse(0.0));
                        }
                ));
    }

    /**
     * Computes the "momentane Messwerte" (current readings) for a list of rooms.
     *
     * <p>For each room, the most recent measurement per metric is taken. The values from
     * all rooms are then averaged using a room-fair mean (each room contributes equally,
     * regardless of sensor count). Rooms with no measurements for a metric are excluded.</p>
     *
     * <p>This is separate from the windowed average returned by
     * {@link #computeAvgMetricsForRooms} and reflects the current state of conditions,
     * as required by §1.5.3 ("momentane Messwerte") for department/company views.</p>
     */
    private Map<Metric, Double> computeLatestMetricsForRooms(List<Room> rooms) {
        if (rooms.isEmpty()) return Collections.emptyMap();

        return Arrays.stream(Metric.values())
                .collect(Collectors.toMap(
                        metric -> metric,
                        metric -> {

                            List<Double> latestPerRoom = rooms.stream()
                                    .map(r -> measurementService
                                            .getFiltered(r.getId(), metric,
                                                    LocalDateTime.now().minusHours(12),
                                                    LocalDateTime.now())
                                            .stream()
                                            .max(Comparator.comparing(Measurement::getTimestamp))
                                            .map(m -> (double) m.getMeasurement()))
                                    .filter(Optional::isPresent)
                                    .map(Optional::get)
                                    .toList();

                            return round2(latestPerRoom.stream()
                                    .mapToDouble(Double::doubleValue)
                                    .average()
                                    .orElse(0.0));
                        }
                ));
    }

    /**
     * Builds a {@link ViolationSummaryDTO} from a raw list of violations.
     *
     * <p>When {@code anonymize} is {@code true} (MANAGEMENT role) the {@code byRoom} list is
     * intentionally left empty so that violations cannot be traced back to individual rooms.</p>
     */
    private ViolationSummaryDTO buildViolationSummary(List<ThresholdViolation> violations,
                                                      List<Long> roomIds,
                                                      List<Room> rooms,
                                                      boolean anonymize) {
        int total = violations.size();
        int active = (int) violations.stream()
                .filter(v -> v.getViolationStatus() == ViolationStatus.ACTIVE).count();
        int resolved = (int) violations.stream()
                .filter(v -> v.getViolationStatus() == ViolationStatus.RESOLVED).count();

        List<ViolationBreakdownDTO> byMetric = Arrays.stream(Metric.values())
                .map(metric -> new ViolationBreakdownDTO(
                        metric.name(),
                        (int) violations.stream()
                                .filter(v -> v.getMetric() == metric).count()))
                .filter(dto -> dto.count() > 0)
                .toList();

        List<ViolationBreakdownDTO> byRoom = anonymize
                ? Collections.emptyList()
                : buildByRoomBreakdown(violations, roomIds, rooms);

        return new ViolationSummaryDTO(total, active, resolved, byMetric, byRoom);
    }

    private List<ViolationBreakdownDTO> buildByRoomBreakdown(List<ThresholdViolation> violations,
                                                             List<Long> roomIds,
                                                             List<Room> rooms) {

        Map<Long, String> roomNameById = rooms
                .stream()
                .collect(Collectors.toMap(Room::getId, Room::getName));

        return roomIds.stream()
                .map(rid -> new ViolationBreakdownDTO(
                        roomNameById.getOrDefault(rid, "Room " + rid),
                        (int) violations.stream()
                                .filter(v -> v.getRoom() != null
                                        && rid.equals(v.getRoom().getId()))
                                .count()))
                .filter(dto -> dto.count() > 0)
                .toList();
    }

    private void validateRange(LocalDateTime from, LocalDateTime to) {
        if (from != null && to != null && from.isAfter(to)) {
            throw new BadRequestException("Invalid date range: 'from' must be before 'to'.");
        }
    }

    private double round2(double value) {
        return Math.round(value * 100.0) / 100.0;
    }
}