export const ROUTES = {
    HOME: '/',
    MANAGE_USERS: '/manage-users',
    LOGIN: '/login',
    LOGOUT: '/logout',
    PROFILE: '/profile',
    DASHBOARD: '/dashboard',
    DASHBOARD_HISTORY: '/dashboard/:roomId/history',
    ABSENCE: '/absence',
    DEPARTMENT_DASHBOARD: '/department',
    DEPARTMENT_ABSENCES: '/department/absences',
    DEPARTMENT_ALERTS: '/department/alerts',
    MANAGEMENT_DASHBOARD: '/management',
    ROOMS: '/rooms',
    THRESHOLDS: '/thresholds',
    DEVICES: '/devices',
    BUILDINGS: '/buildings',
    DEPARTMENTS: '/departments',
} as const;
