--
-- PostgreSQL database dump
--

\restrict giYW9cTSEcSSjMpYE8HWorszu1T5X3HJzdmVn2eveuNIkKlyos3oisEfIUtC4zJ

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: sa
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO sa;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: sa
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: absences; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.absences (
    id bigint NOT NULL,
    absence_status character varying(255),
    absence_type character varying(255),
    end_date timestamp(6) without time zone,
    start_date timestamp(6) without time zone,
    userx_id bigint NOT NULL,
    CONSTRAINT absences_absence_status_check CHECK (((absence_status)::text = ANY (ARRAY[('PLANNED'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text, ('CANCELLED'::character varying)::text]))),
    CONSTRAINT absences_absence_type_check CHECK (((absence_type)::text = ANY (ARRAY[('HOLIDAY'::character varying)::text, ('SICKNESS'::character varying)::text, ('PARENTAL_LEAVE'::character varying)::text, ('OTHER'::character varying)::text])))
);


ALTER TABLE public.absences OWNER TO sa;

--
-- Name: absences_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.absences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: addresses; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.addresses (
    id bigint NOT NULL,
    city character varying(255),
    country character varying(255),
    extra character varying(255),
    house_number character varying(255),
    street character varying(255),
    zip_code character varying(255)
);


ALTER TABLE public.addresses OWNER TO sa;

--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buildings; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.buildings (
    id bigint NOT NULL,
    name character varying(255),
    address_id bigint
);


ALTER TABLE public.buildings OWNER TO sa;

--
-- Name: buildings_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.buildings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buildings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: climatehint_threshold; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.climatehint_threshold (
    climatehint_id bigint NOT NULL,
    threshold_id bigint NOT NULL
);


ALTER TABLE public.climatehint_threshold OWNER TO sa;

--
-- Name: climatehints; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.climatehints (
    id bigint NOT NULL,
    hint_text character varying(255),
    metric smallint,
    CONSTRAINT climatehints_metric_check CHECK (((metric >= 0) AND (metric <= 3)))
);


ALTER TABLE public.climatehints OWNER TO sa;

--
-- Name: climatehints_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.climatehints ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.climatehints_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    name character varying(255),
    userx_id bigint
);


ALTER TABLE public.departments OWNER TO sa;

--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employeeprofile; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.employeeprofile (
    id bigint NOT NULL,
    department_id bigint,
    room_id bigint,
    userx_id bigint NOT NULL
);


ALTER TABLE public.employeeprofile OWNER TO sa;

--
-- Name: employeeprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.employeeprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employeeprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: measurement; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.measurement (
    id bigint NOT NULL,
    measurement real,
    metric character varying(255),
    "timestamp" timestamp(6) without time zone,
    room_id bigint NOT NULL,
    sensorstation_id bigint NOT NULL,
    CONSTRAINT measurement_metric_check CHECK (((metric)::text = ANY (ARRAY[('HUMIDITY'::character varying)::text, ('TEMPERATURE'::character varying)::text, ('PRESSURE'::character varying)::text, ('IAQ'::character varying)::text])))
);


ALTER TABLE public.measurement OWNER TO sa;

--
-- Name: measurement_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raspberrypis; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.raspberrypis (
    id bigint NOT NULL,
    device_status character varying(255),
    host_name character varying(255),
    ip_address character varying(255),
    room_id bigint,
    CONSTRAINT raspberrypis_device_status_check CHECK (((device_status)::text = ANY (ARRAY[('ONLINE'::character varying)::text, ('OFFLINE'::character varying)::text, ('MAINTENANCE'::character varying)::text, ('DEGRADED'::character varying)::text, ('DECOMMISSIONED'::character varying)::text, ('AVAILABLE'::character varying)::text, ('CONNECTED'::character varying)::text, ('CONNECTION_FAILED'::character varying)::text])))
);


ALTER TABLE public.raspberrypis OWNER TO sa;

--
-- Name: raspberrypis_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.raspberrypis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raspberrypis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rooms; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    active boolean NOT NULL,
    name character varying(255),
    privacy_mode boolean,
    room_type character varying(255),
    building_id bigint,
    department_id bigint,
    CONSTRAINT rooms_room_type_check CHECK (((room_type)::text = ANY (ARRAY[('OFFICE'::character varying)::text, ('COMMON_AREAS'::character varying)::text])))
);


ALTER TABLE public.rooms OWNER TO sa;

--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sensorstations; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.sensorstations (
    id bigint NOT NULL,
    ble_mac character varying(255),
    device_status character varying(255),
    measurement_interval integer,
    name character varying(255),
    raspberry_pi_id bigint,
    room_id bigint NOT NULL,
    CONSTRAINT sensorstations_device_status_check CHECK (((device_status)::text = ANY (ARRAY[('ONLINE'::character varying)::text, ('OFFLINE'::character varying)::text, ('MAINTENANCE'::character varying)::text, ('DEGRADED'::character varying)::text, ('DECOMMISSIONED'::character varying)::text, ('AVAILABLE'::character varying)::text, ('CONNECTED'::character varying)::text, ('CONNECTION_FAILED'::character varying)::text])))
);


ALTER TABLE public.sensorstations OWNER TO sa;

--
-- Name: sensorstations_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.sensorstations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sensorstations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: threshold_violation_measurement; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.threshold_violation_measurement (
    threshold_violation_id bigint NOT NULL,
    measurement_id bigint NOT NULL
);


ALTER TABLE public.threshold_violation_measurement OWNER TO sa;

--
-- Name: thresholds; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.thresholds (
    id bigint NOT NULL,
    bound_value real,
    enabled boolean NOT NULL,
    metric character varying(255),
    threshold_type character varying(255),
    room_id bigint NOT NULL,
    CONSTRAINT thresholds_metric_check CHECK (((metric)::text = ANY (ARRAY[('HUMIDITY'::character varying)::text, ('TEMPERATURE'::character varying)::text, ('PRESSURE'::character varying)::text, ('IAQ'::character varying)::text]))),
    CONSTRAINT thresholds_threshold_type_check CHECK (((threshold_type)::text = ANY (ARRAY[('LOWER'::character varying)::text, ('UPPER'::character varying)::text])))
);


ALTER TABLE public.thresholds OWNER TO sa;

--
-- Name: thresholds_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.thresholds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thresholds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: thresholdviolations; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.thresholdviolations (
    id bigint NOT NULL,
    end_time timestamp(6) without time zone,
    metric character varying(255),
    start_time timestamp(6) without time zone,
    value real,
    violation_status character varying(255),
    room_id bigint NOT NULL,
    threshold_id bigint NOT NULL,
    CONSTRAINT thresholdviolations_metric_check CHECK (((metric)::text = ANY (ARRAY[('HUMIDITY'::character varying)::text, ('TEMPERATURE'::character varying)::text, ('PRESSURE'::character varying)::text, ('IAQ'::character varying)::text]))),
    CONSTRAINT thresholdviolations_violation_status_check CHECK (((violation_status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('RESOLVED'::character varying)::text, ('DISABLED'::character varying)::text])))
);


ALTER TABLE public.thresholdviolations OWNER TO sa;

--
-- Name: thresholdviolations_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.thresholdviolations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thresholdviolations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userx; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.userx (
    id bigint NOT NULL,
    create_date timestamp(6) without time zone NOT NULL,
    email character varying(255),
    enabled boolean NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    phone character varying(255),
    update_date timestamp(6) without time zone,
    username character varying(100) NOT NULL,
    create_user_id bigint NOT NULL,
    update_user_id bigint
);


ALTER TABLE public.userx OWNER TO sa;

--
-- Name: userx_id_seq; Type: SEQUENCE; Schema: public; Owner: sa
--

ALTER TABLE public.userx ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.userx_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userx_userx_role; Type: TABLE; Schema: public; Owner: sa
--

CREATE TABLE public.userx_userx_role (
    userx_id bigint NOT NULL,
    roles character varying(255),
    CONSTRAINT userx_userx_role_roles_check CHECK (((roles)::text = ANY (ARRAY[('SYSTEM_ADMIN'::character varying)::text, ('BUILDING_ADMIN'::character varying)::text, ('DEPARTMENT_LEAD'::character varying)::text, ('MANAGEMENT'::character varying)::text, ('EMPLOYEE'::character varying)::text])))
);


ALTER TABLE public.userx_userx_role OWNER TO sa;

--
-- Data for Name: absences; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.absences (id, absence_status, absence_type, end_date, start_date, userx_id) FROM stdin;
1	PLANNED	SICKNESS	2026-04-12 18:00:00	2026-04-10 09:00:00	2
2	PLANNED	SICKNESS	2026-04-12 18:00:00	2026-04-10 09:00:00	3
3	PLANNED	PARENTAL_LEAVE	2026-04-09 18:00:00	2026-04-08 09:00:00	3
4	PLANNED	SICKNESS	2026-04-06 17:00:00	2026-04-05 08:00:00	1
6	PLANNED	HOLIDAY	2026-05-09 18:00:00	2026-05-05 08:00:00	5
7	PLANNED	HOLIDAY	2026-05-09 18:00:00	2026-05-05 08:00:00	6
11	PLANNED	SICKNESS	2026-03-21 18:00:00	2026-03-20 08:00:00	9
5	APPROVED	HOLIDAY	2026-01-17 18:00:00	2026-01-15 08:00:00	5
8	APPROVED	SICKNESS	2026-02-04 18:00:00	2026-02-03 08:00:00	6
9	APPROVED	HOLIDAY	2026-02-14 18:00:00	2026-02-10 08:00:00	7
10	APPROVED	PARENTAL_LEAVE	2026-03-05 18:00:00	2026-03-01 08:00:00	8
12	APPROVED	HOLIDAY	2026-04-03 18:00:00	2026-04-01 08:00:00	11
13	APPROVED	HOLIDAY	2026-04-18 18:00:00	2026-04-14 08:00:00	10
14	APPROVED	OTHER	2026-01-31 18:00:00	2026-01-27 08:00:00	12
15	APPROVED	SICKNESS	2026-02-26 18:00:00	2026-02-24 08:00:00	13
16	APPROVED	HOLIDAY	2026-03-12 18:00:00	2026-03-10 08:00:00	14
\.


--
-- Data for Name: addresses; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.addresses (id, city, country, extra, house_number, street, zip_code) FROM stdin;
2	Innsbruck 	Austria	Campus West	21	Technikerstraße	6020
3	Innsbruck	Austria	Main Campus	52	Innrain	6020
1	Milano	Italy	Primary Address	40	Viale Murillo	4999
4	Munich	Germany	HQ South	4	Maximilianstraße	80333
\.


--
-- Data for Name: buildings; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.buildings (id, name, address_id) FROM stdin;
1	Old IT Building	1
2	Tech Tower	2
3	Main Office	3
4	South HQ	4
\.


--
-- Data for Name: climatehint_threshold; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.climatehint_threshold (climatehint_id, threshold_id) FROM stdin;
\.


--
-- Data for Name: climatehints; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.climatehints (id, hint_text, metric) FROM stdin;
1	Use a reverse-water-sprayer	0
3	Open the windows of the room	1
4	Lower the blinds	1
5	Check if the heating is turned on	1
6	Turn on the dehumidifier	0
7	Ensure the windows are sealed properly	2
8	Ventilate the room immediately by opening the windows.	3
9	Check if the air filter needs replacing	3
10	Barometric pressure anaomaly - check HVAC settings	2
\.


--
-- Data for Name: departments; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.departments (id, name, userx_id) FROM stdin;
1	Research (2)	1
2	Sales	3
3	Management	2
4	Engineering	5
5	HR	10
\.


--
-- Data for Name: employeeprofile; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.employeeprofile (id, department_id, room_id, userx_id) FROM stdin;
1	1	1	1
2	1	1	2
3	1	2	4
4	3	8	3
5	3	5	5
6	4	9	6
7	4	10	7
8	4	10	8
9	5	13	9
10	5	14	10
11	5	13	11
12	3	5	12
13	3	5	13
14	3	6	14
\.


--
-- Data for Name: measurement; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.measurement (id, measurement, metric, "timestamp", room_id, sensorstation_id) FROM stdin;
\.


--
-- Data for Name: raspberrypis; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.raspberrypis (id, device_status, host_name, ip_address, room_id) FROM stdin;
10	OFFLINE	rpi-eng-c	192.168.2.12	11
1	OFFLINE	rpi-room1	192.168.1.10	1
2	OFFLINE	rpi-common1	192.168.1.11	2
3	OFFLINE	rpi-sales-common	192.168.5.11	3
4	OFFLINE	rpi-sales-a	192.168.5.10	4
5	OFFLINE	rpi-mgmt-a	192.168.4.10	5
6	OFFLINE	rpi-mgmt-b	192.168.4.11	6
7	OFFLINE	rpi-mgmt-common	192.168.4.12	7
8	OFFLINE	rpi-eng-a	192.168.2.10	9
9	OFFLINE	rpi-eng-b	192.168.2.11	10
11	OFFLINE	rpi-eng-common	192.168.2.13	12
13	OFFLINE	rpi-hr-b	192.168.3.11	14
12	OFFLINE	rpi-hr-a	192.168.3.10	13
14	OFFLINE	rpi-hr-common	192.168.3.12	15
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.rooms (id, active, name, privacy_mode, room_type, building_id, department_id) FROM stdin;
1	t	Room 1	f	OFFICE	1	1
2	t	Common Area 1	f	COMMON_AREAS	1	1
3	t	Sales Common Area	f	COMMON_AREAS	4	2
4	t	Sales Office A	f	OFFICE	4	2
5	t	Mgmt Office A	f	OFFICE	3	3
6	t	Mgmt Office B	f	OFFICE	3	3
7	t	Mgmt Common Area	f	COMMON_AREAS	3	3
8	t	Mgmt Common Area 2	f	COMMON_AREAS	3	3
9	t	Eng Office A	f	OFFICE	2	4
10	t	Eng Office B	f	OFFICE	2	4
11	t	Eng Office C	f	OFFICE	2	4
12	t	Eng Common Area	f	COMMON_AREAS	2	4
13	t	HR Office A	f	OFFICE	3	5
14	t	HR Office B	f	OFFICE	3	5
15	t	HR Common Area	f	COMMON_AREAS	3	5
\.


--
-- Data for Name: sensorstations; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.sensorstations (id, ble_mac, device_status, measurement_interval, name, raspberry_pi_id, room_id) FROM stdin;
1	02:FF:5E:ED:01:03	CONNECTION_FAILED	15	Eng-C-S1	10	11
2	02:FF:5E:ED:00:01	CONNECTION_FAILED	5	Station A	1	1
3	02:FF:5E:ED:00:02	CONNECTION_FAILED	10	Station B	2	2
4	02:FF:5E:ED:04:10	CONNECTION_FAILED	25	Sales-Common-S1	3	3
5	02:FF:5E:ED:04:01	CONNECTION_FAILED	11	Sales-A-S1	4	4
6	02:FF:5E:ED:03:01	CONNECTION_FAILED	9	Mgmt-A-S1	5	5
7	02:FF:5E:ED:03:02	CONNECTION_FAILED	30	Mgmt-B-S1	6	6
8	02:FF:5E:ED:03:10	CONNECTION_FAILED	18	Mgmt-Common-S1	7	7
9	02:FF:5E:ED:01:01	CONNECTION_FAILED	4	Eng-A-S1	8	9
10	02:FF:5E:ED:01:02	CONNECTION_FAILED	6	Eng-B-S1	9	10
11	02:FF:5E:ED:01:10	CONNECTION_FAILED	8	Eng-Common-S1	11	12
12	02:FF:5E:ED:02:02	CONNECTION_FAILED	7	HR-B-S1	13	14
13	02:FF:5E:ED:02:01	CONNECTION_FAILED	12	HR-A-S1	12	13
14	02:FF:5E:ED:02:10	CONNECTION_FAILED	20	HR-Common-S1	14	15
15	02:FF:5E:ED:01:04	CONNECTION_FAILED	13	Eng-A-S2	8	9
16	02:FF:5E:ED:01:05	CONNECTION_FAILED	17	Eng-A-S3	8	9
\.


--
-- Data for Name: threshold_violation_measurement; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.threshold_violation_measurement (threshold_violation_id, measurement_id) FROM stdin;
\.


--
-- Data for Name: thresholds; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.thresholds (id, bound_value, enabled, metric, threshold_type, room_id) FROM stdin;
1	60	t	HUMIDITY	UPPER	1
2	27	t	TEMPERATURE	UPPER	9
3	18	t	TEMPERATURE	LOWER	9
4	65	t	HUMIDITY	UPPER	9
5	400	t	IAQ	UPPER	9
6	27	t	TEMPERATURE	UPPER	10
7	65	t	HUMIDITY	UPPER	10
8	400	t	IAQ	UPPER	10
9	26	t	TEMPERATURE	UPPER	13
10	60	t	HUMIDITY	UPPER	13
11	350	t	IAQ	UPPER	13
12	26	t	TEMPERATURE	UPPER	14
13	60	t	HUMIDITY	UPPER	14
14	55	t	HUMIDITY	UPPER	5
15	300	t	IAQ	UPPER	5
16	28	t	TEMPERATURE	UPPER	4
17	70	t	HUMIDITY	UPPER	4
18	500	t	IAQ	UPPER	4
\.


--
-- Data for Name: thresholdviolations; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.thresholdviolations (id, end_time, metric, start_time, value, violation_status, room_id, threshold_id) FROM stdin;
1	2026-04-13 11:00:00	TEMPERATURE	2026-04-13 10:00:00	28	RESOLVED	1	1
2	\N	HUMIDITY	2026-04-23 07:45:00	65	ACTIVE	1	1
3	\N	HUMIDITY	2026-04-23 06:30:00	63.5	ACTIVE	13	10
4	2026-02-20 19:00:00	TEMPERATURE	2026-02-20 14:00:00	27.1	RESOLVED	14	12
5	2026-03-20 18:00:00	TEMPERATURE	2026-03-20 12:00:00	27.8	RESOLVED	10	6
6	\N	IAQ	2026-04-22 14:00:00	431	ACTIVE	9	5
7	2026-03-15 16:00:00	TEMPERATURE	2026-03-15 11:30:00	26.9	RESOLVED	14	12
8	\N	TEMPERATURE	2026-04-22 12:00:00	29.2	ACTIVE	4	16
9	2026-01-25 18:00:00	IAQ	2026-01-25 12:00:00	512	RESOLVED	4	18
10	2026-03-08 15:30:00	HUMIDITY	2026-03-08 09:00:00	69.1	RESOLVED	9	4
11	2026-01-30 17:00:00	IAQ	2026-01-30 13:00:00	362	RESOLVED	13	11
12	\N	HUMIDITY	2026-04-21 08:00:00	72.3	ACTIVE	10	7
13	2026-02-28 17:30:00	IAQ	2026-02-28 13:00:00	498	RESOLVED	4	18
14	2026-02-15 16:00:00	TEMPERATURE	2026-02-15 11:00:00	28.4	RESOLVED	9	2
\.


--
-- Data for Name: userx; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.userx (id, create_date, email, enabled, first_name, last_name, password, phone, update_date, username, create_user_id, update_user_id) FROM stdin;
2	2024-01-01 00:00:00	susi.kaufgern@example.com	t	Susi	Kaufgern	{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS	+43 123456789	2026-05-23 20:33:15.73157	user1	1	1
1	2024-01-01 00:00:00	admin.istrator@example.com	t	Admin	Istrator	{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS	+43 123456789	2026-05-23 21:24:38.401571	admin	2	1
4	2026-05-23 20:36:55.436763	max.mustermann@example.com	t	Max	Mustermann	{bcrypt}$2a$10$h/USGzTJ7r.tiR091UYCEunurdUM1vsez4NAluHXmv7wxQC5cjfWC	+43 123456789	2026-05-23 20:36:55.43678	user2	1	\N
3	2026-05-23 18:45:44.857729	elvis.theking@example.com	t	Elvis	The King	{bcrypt}$2a$10$O.58lu32GgXRJpNLpCoQbOHWQcx9SKxschzqFEWO7MCGAA9q9Lfie	+43 123456789	2026-05-23 20:43:01.789277	elvis	1	1
5	2026-05-23 20:44:15.978575	anna.berger@example.com	t	Anna	Berger	{bcrypt}$2a$10$rJJ0K.2aKBNUIf141KhjM.cFejxYAWGfKzJ3/b9Tckd/JIaDjOyi6	+43 123456789	2026-05-23 20:44:45.860691	anna	1	1
6	2026-05-23 20:47:59.023068	ben.schmidt@example.com	t	Ben	Schmidt	{bcrypt}$2a$10$u7C976J4QV5ETqj9kfJ98OmvsEkIR2EmMIGVrWhiGWk595kIb/dYO	+43 123456789	2026-05-23 20:47:59.023088	ben	1	\N
7	2026-05-23 20:49:25.46353	clara.huber@example.com	t	Clara	Huber	{bcrypt}$2a$10$0S3v.l4dTvnmvZC570SIPOmcSdW3seQeQYj9UdU3KzSaxmNsrIikq	+43 123456789	2026-05-23 20:49:25.463542	clara	1	\N
8	2026-05-23 20:51:28.663468	david.müller@example.com	t	David	Müller	{bcrypt}$2a$10$RzzkCvY4yHE0wF9upHk63eIxlVpH7rWDCmFG1DWBBeZeaVRrel3GS	+43 123456789	2026-05-23 20:51:28.663488	david	1	\N
9	2026-05-23 20:55:18.784428	eva.kowalski@example.com	t	Eva	Kowalski	{bcrypt}$2a$10$tI1Ig2781bQj1dCLwoZ4WOi8G4WJX99OEU4hPy4skR.Zk6fgcAfye	+43 123456789	2026-05-23 20:55:59.514855	eva	1	1
10	2026-05-23 20:57:03.917727	greta.fischer@example.com	t	Greta	Fischer	{bcrypt}$2a$10$gCTdyRe.YriWh/fBYJOkpeQwQr56qUM5Zjr1oZyDjfk7vB82XneEW	+43 123456789	2026-05-23 20:57:34.553575	greta	1	1
11	2026-05-23 20:58:35.888549	felix.wagner@example.com	t	Felix	Wagner	{bcrypt}$2a$10$NJyubtQeZZW57EqW8A4/u.JV1DabBIXyKp9VwOhTM7oquQSc8OhCC	+43 123456789	2026-05-23 20:58:35.888558	felix	1	\N
12	2026-05-23 20:59:38.645567	hans.bauer@example.com	t	Hans	Bauer	{bcrypt}$2a$10$CMROC/2EFcNPE9RhqjIARusOd8zaMaA/aC6GUW4aviq7P.4YMDWuW	+43 123456789	2026-05-23 20:59:38.645577	hans	1	\N
13	2026-05-23 21:00:19.116248	iris.klein@example.com	t	Iris	Klein	{bcrypt}$2a$10$OqYeNroz7rUduIVwUiCdReptF37tofewMBZPu7FmrCrWyC1dGbNfu	+43 123456789	2026-05-23 21:00:19.11626	iris	1	\N
14	2026-05-23 21:02:41.832999	jonas.wolf@example.com	t	Jonas	Wolf	{bcrypt}$2a$10$DjF1BQ6sWL438c1gSWOjAuvity6KwyK3dKebQkAAngHlfCkKu4Vg2	+43 123456789	2026-05-23 21:02:41.83301	jonas	1	\N
\.


--
-- Data for Name: userx_userx_role; Type: TABLE DATA; Schema: public; Owner: sa
--

COPY public.userx_userx_role (userx_id, roles) FROM stdin;
2	MANAGEMENT
2	EMPLOYEE
4	EMPLOYEE
2	DEPARTMENT_LEAD
3	SYSTEM_ADMIN
3	DEPARTMENT_LEAD
3	EMPLOYEE
5	EMPLOYEE
5	DEPARTMENT_LEAD
6	EMPLOYEE
7	EMPLOYEE
8	EMPLOYEE
9	EMPLOYEE
9	BUILDING_ADMIN
10	EMPLOYEE
10	DEPARTMENT_LEAD
11	EMPLOYEE
12	EMPLOYEE
13	MANAGEMENT
13	EMPLOYEE
14	EMPLOYEE
1	SYSTEM_ADMIN
1	EMPLOYEE
1	BUILDING_ADMIN
1	DEPARTMENT_LEAD
\.


--
-- Name: absences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.absences_id_seq', 16, true);


--
-- Name: addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.addresses_id_seq', 4, true);


--
-- Name: buildings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.buildings_id_seq', 4, true);


--
-- Name: climatehints_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.climatehints_id_seq', 10, true);


--
-- Name: departments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.departments_id_seq', 5, true);


--
-- Name: employeeprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.employeeprofile_id_seq', 14, true);


--
-- Name: measurement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.measurement_id_seq', 26476, true);


--
-- Name: raspberrypis_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.raspberrypis_id_seq', 14, true);


--
-- Name: rooms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.rooms_id_seq', 15, true);


--
-- Name: sensorstations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.sensorstations_id_seq', 16, true);


--
-- Name: thresholds_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.thresholds_id_seq', 18, true);


--
-- Name: thresholdviolations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.thresholdviolations_id_seq', 14, true);


--
-- Name: userx_id_seq; Type: SEQUENCE SET; Schema: public; Owner: sa
--

SELECT pg_catalog.setval('public.userx_id_seq', 14, true);


--
-- Name: absences absences_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.absences
    ADD CONSTRAINT absences_pkey PRIMARY KEY (id);


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: buildings buildings_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.buildings
    ADD CONSTRAINT buildings_pkey PRIMARY KEY (id);


--
-- Name: climatehint_threshold climatehint_threshold_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.climatehint_threshold
    ADD CONSTRAINT climatehint_threshold_pkey PRIMARY KEY (climatehint_id, threshold_id);


--
-- Name: climatehints climatehints_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.climatehints
    ADD CONSTRAINT climatehints_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: employeeprofile employeeprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.employeeprofile
    ADD CONSTRAINT employeeprofile_pkey PRIMARY KEY (id);


--
-- Name: measurement measurement_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT measurement_pkey PRIMARY KEY (id);


--
-- Name: raspberrypis raspberrypis_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.raspberrypis
    ADD CONSTRAINT raspberrypis_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);


--
-- Name: sensorstations sensorstations_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sensorstations
    ADD CONSTRAINT sensorstations_pkey PRIMARY KEY (id);


--
-- Name: thresholds thresholds_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.thresholds
    ADD CONSTRAINT thresholds_pkey PRIMARY KEY (id);


--
-- Name: thresholdviolations thresholdviolations_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.thresholdviolations
    ADD CONSTRAINT thresholdviolations_pkey PRIMARY KEY (id);


--
-- Name: buildings uk7m2pe3n3t2ichnr45yqegfbqa; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.buildings
    ADD CONSTRAINT uk7m2pe3n3t2ichnr45yqegfbqa UNIQUE (address_id);


--
-- Name: userx ukeqay1mmomyiwpw7d5aeqsees9; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.userx
    ADD CONSTRAINT ukeqay1mmomyiwpw7d5aeqsees9 UNIQUE (username);


--
-- Name: raspberrypis ukokje5boym56xx9e7ync78w62j; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.raspberrypis
    ADD CONSTRAINT ukokje5boym56xx9e7ync78w62j UNIQUE (room_id);


--
-- Name: employeeprofile ukru7x3yraijhvxlvfe70xhnlbb; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.employeeprofile
    ADD CONSTRAINT ukru7x3yraijhvxlvfe70xhnlbb UNIQUE (userx_id);


--
-- Name: userx userx_pkey; Type: CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.userx
    ADD CONSTRAINT userx_pkey PRIMARY KEY (id);


--
-- Name: userx_userx_role fk7xbt0nb5aek0b4mfgl73j3k7b; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.userx_userx_role
    ADD CONSTRAINT fk7xbt0nb5aek0b4mfgl73j3k7b FOREIGN KEY (userx_id) REFERENCES public.userx(id);


--
-- Name: sensorstations fk8u0vuxji2ko9yuhc9vty7nmwp; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sensorstations
    ADD CONSTRAINT fk8u0vuxji2ko9yuhc9vty7nmwp FOREIGN KEY (raspberry_pi_id) REFERENCES public.raspberrypis(id);


--
-- Name: thresholds fkab5ew8ngxdw6awyuramotekro; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.thresholds
    ADD CONSTRAINT fkab5ew8ngxdw6awyuramotekro FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: userx fkdcgcwh5gh0ukw11kx90huv0p3; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.userx
    ADD CONSTRAINT fkdcgcwh5gh0ukw11kx90huv0p3 FOREIGN KEY (create_user_id) REFERENCES public.userx(id);


--
-- Name: threshold_violation_measurement fkdr45yh1xvajl6hmale88m8ipo; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.threshold_violation_measurement
    ADD CONSTRAINT fkdr45yh1xvajl6hmale88m8ipo FOREIGN KEY (threshold_violation_id) REFERENCES public.thresholdviolations(id);


--
-- Name: climatehint_threshold fkea11g08kqhajqmehv6oveld4f; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.climatehint_threshold
    ADD CONSTRAINT fkea11g08kqhajqmehv6oveld4f FOREIGN KEY (climatehint_id) REFERENCES public.climatehints(id);


--
-- Name: measurement fkixudq324nawn7jmfo2vyjclmh; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT fkixudq324nawn7jmfo2vyjclmh FOREIGN KEY (sensorstation_id) REFERENCES public.sensorstations(id);


--
-- Name: absences fkj0f009n459lpfs7yt5xhshpo0; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.absences
    ADD CONSTRAINT fkj0f009n459lpfs7yt5xhshpo0 FOREIGN KEY (userx_id) REFERENCES public.userx(id);


--
-- Name: sensorstations fkk3q26jmv4c06bki3onn5m1ayp; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.sensorstations
    ADD CONSTRAINT fkk3q26jmv4c06bki3onn5m1ayp FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: climatehint_threshold fkkb4fto1jeidjedagn9y1dwcif; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.climatehint_threshold
    ADD CONSTRAINT fkkb4fto1jeidjedagn9y1dwcif FOREIGN KEY (threshold_id) REFERENCES public.thresholds(id);


--
-- Name: thresholdviolations fklm0iiqs5se40o32xjuuh0smd6; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.thresholdviolations
    ADD CONSTRAINT fklm0iiqs5se40o32xjuuh0smd6 FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: rooms fkmnnwsm0xvdd30vps6hpm92nm6; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fkmnnwsm0xvdd30vps6hpm92nm6 FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: employeeprofile fko67ix9m6fape369qgf05biie9; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.employeeprofile
    ADD CONSTRAINT fko67ix9m6fape369qgf05biie9 FOREIGN KEY (userx_id) REFERENCES public.userx(id);


--
-- Name: rooms fkojgn0sxhkfxd7pmmojnem9r4q; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fkojgn0sxhkfxd7pmmojnem9r4q FOREIGN KEY (building_id) REFERENCES public.buildings(id);


--
-- Name: raspberrypis fkosuia3j7equ4v5fh5fi5y9up; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.raspberrypis
    ADD CONSTRAINT fkosuia3j7equ4v5fh5fi5y9up FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: employeeprofile fkp27y2nkikvdvltporiy7dcue7; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.employeeprofile
    ADD CONSTRAINT fkp27y2nkikvdvltporiy7dcue7 FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: buildings fkp95lykb389qd8rw53byhlr75l; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.buildings
    ADD CONSTRAINT fkp95lykb389qd8rw53byhlr75l FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: threshold_violation_measurement fkpcr6j1m8oqydyhcetu48a59kv; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.threshold_violation_measurement
    ADD CONSTRAINT fkpcr6j1m8oqydyhcetu48a59kv FOREIGN KEY (measurement_id) REFERENCES public.measurement(id);


--
-- Name: thresholdviolations fkq9i8xge8oggqpo7phe3v8o1g5; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.thresholdviolations
    ADD CONSTRAINT fkq9i8xge8oggqpo7phe3v8o1g5 FOREIGN KEY (threshold_id) REFERENCES public.thresholds(id);


--
-- Name: departments fkqxdxga32031ue01gkwoiu92uh; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fkqxdxga32031ue01gkwoiu92uh FOREIGN KEY (userx_id) REFERENCES public.userx(id);


--
-- Name: measurement fkqxtdo777dm48qtd0tsk657yn3; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.measurement
    ADD CONSTRAINT fkqxtdo777dm48qtd0tsk657yn3 FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: employeeprofile fkqxthpr0a22jn1cd4powfgtwt2; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.employeeprofile
    ADD CONSTRAINT fkqxthpr0a22jn1cd4powfgtwt2 FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: userx fkt30x16vcb06xvu4yjd0ux9nw8; Type: FK CONSTRAINT; Schema: public; Owner: sa
--

ALTER TABLE ONLY public.userx
    ADD CONSTRAINT fkt30x16vcb06xvu4yjd0ux9nw8 FOREIGN KEY (update_user_id) REFERENCES public.userx(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: sa
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict giYW9cTSEcSSjMpYE8HWorszu1T5X3HJzdmVn2eveuNIkKlyos3oisEfIUtC4zJ

