-- noinspection SqlNoDataSourceInspectionForFile

-- =========================================
-- 1. Allow NULL temporarily for bootstrap
-- =========================================
ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID DROP NOT NULL;

-- =========================================
-- 2. Insert USERS (idempotent)
-- =========================================

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Admin', 'Istrator', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'admin', NULL, '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME = 'admin');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Susi', 'Kaufgern', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user1', NULL, '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME = 'user1');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Max', 'Mustermann', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user2', NULL, '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME = 'user2');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Elvis', 'The King', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'elvis', NULL, '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME = 'elvis');

-- =========================================
-- 3. Insert USER ROLES (idempotent)
-- =========================================

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'SYSTEM_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='admin') AND ROLES='SYSTEM_ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='admin') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGEMENT'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='user1') AND ROLES='MANAGEMENT');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='user1') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='user2') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'SYSTEM_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='elvis') AND ROLES='SYSTEM_ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='elvis') AND ROLES='EMPLOYEE');

-- =========================================
-- 4. Fix CREATE_USER_ID (safe update)
-- =========================================

UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME IN ('admin', 'user1', 'user2');
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis') WHERE USERNAME = 'elvis';

-- =========================================
-- 5. Re-enable NOT NULL constraint
-- =========================================

ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID SET NOT NULL;

-- ---------------------------------------------------------------------------
-- Extended test data
-- ---------------------------------------------------------------------------

-- =========================================
-- ADDRESSES
-- =========================================

INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
SELECT 'Italy', '4999', 'Something', 'N/A', '81/A', 'Primary Address'
WHERE NOT EXISTS (SELECT 1 FROM ADDRESSES WHERE COUNTRY='Italy' AND ZIP_CODE='4999' AND CITY='Something' AND STREET='N/A' AND HOUSE_NUMBER='81/A' AND EXTRA='Primary Address');

INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
SELECT 'Austria', '6020', 'Innsbruck', 'Technikerstraße', '21', 'Campus West'
WHERE NOT EXISTS (SELECT 1 FROM ADDRESSES WHERE COUNTRY='Austria' AND ZIP_CODE='6020' AND CITY='Innsbruck' AND STREET='Technikerstraße' AND HOUSE_NUMBER='21' AND EXTRA='Campus West');

INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
SELECT 'Austria', '6020', 'Innsbruck', 'Innrain', '52', 'Main Campus'
WHERE NOT EXISTS (SELECT 1 FROM ADDRESSES WHERE COUNTRY='Austria' AND ZIP_CODE='6020' AND CITY='Innsbruck' AND STREET='Innrain' AND HOUSE_NUMBER='52' AND EXTRA='Main Campus');

INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
SELECT 'Germany', '80333', 'Munich', 'Maximilianstraße', '4', 'HQ South'
WHERE NOT EXISTS (SELECT 1 FROM ADDRESSES WHERE COUNTRY='Germany' AND ZIP_CODE='80333' AND CITY='Munich' AND STREET='Maximilianstraße' AND HOUSE_NUMBER='4' AND EXTRA='HQ South');

-- =========================================
-- BUILDINGS
-- =========================================

INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
SELECT 'Still OLD IT', (SELECT ID FROM ADDRESSES WHERE COUNTRY='Italy' AND ZIP_CODE='4999' AND CITY='Something' AND STREET='N/A' AND HOUSE_NUMBER='81/A' AND EXTRA='Primary Address')
WHERE NOT EXISTS (SELECT 1 FROM BUILDINGS WHERE NAME='Still OLD IT');

INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
SELECT 'Tech Tower', (SELECT ID FROM ADDRESSES WHERE CITY='Innsbruck' AND STREET='Technikerstraße')
WHERE NOT EXISTS (SELECT 1 FROM BUILDINGS WHERE NAME='Tech Tower');

INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
SELECT 'Main Office', (SELECT ID FROM ADDRESSES WHERE CITY='Innsbruck' AND STREET='Innrain')
WHERE NOT EXISTS (SELECT 1 FROM BUILDINGS WHERE NAME='Main Office');

INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
SELECT 'South HQ', (SELECT ID FROM ADDRESSES WHERE CITY='Munich')
WHERE NOT EXISTS (SELECT 1 FROM BUILDINGS WHERE NAME='South HQ');

-- =========================================
-- DEPARTMENTS
-- =========================================

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
SELECT 'Research (2)', (SELECT ID FROM USERX WHERE USERNAME='admin')
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE NAME='Research (2)');

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
SELECT 'Sales', (SELECT ID FROM USERX WHERE USERNAME='elvis')
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE NAME='Sales');

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
SELECT 'Engineering', (SELECT ID FROM USERX WHERE USERNAME='admin')
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE NAME='Engineering');

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
SELECT 'HR', (SELECT ID FROM USERX WHERE USERNAME='admin')
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE NAME='HR');

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
SELECT 'Management', (SELECT ID FROM USERX WHERE USERNAME='user1')
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS WHERE NAME='Management');

-- =========================================
-- EXTENDED USERS (anna … jonas)
-- =========================================

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Anna', 'Berger', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'anna', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='anna');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Ben', 'Schmidt', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'ben', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='ben');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Clara', 'Huber', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'clara', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='clara');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'David', 'Müller', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'david', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='david');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Eva', 'Kowalski', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'eva', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='eva');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Felix', 'Wagner', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'felix', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='felix');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Greta', 'Fischer', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'greta', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='greta');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Hans', 'Bauer', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'hans', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='hans');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Iris', 'Klein', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'iris', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='iris');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
SELECT TRUE, 'Jonas', 'Wolf', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'jonas', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00'
WHERE NOT EXISTS (SELECT 1 FROM USERX WHERE USERNAME='jonas');

-- Extended user roles

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='anna'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='anna') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='anna'), 'DEPARTMENT_LEAD'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='anna') AND ROLES='DEPARTMENT_LEAD');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='ben'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='ben') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='clara'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='clara') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='david'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='david') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='eva'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='eva') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='eva'), 'BUILDING_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='eva') AND ROLES='BUILDING_ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='felix'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='felix') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='greta'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='greta') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='greta'), 'DEPARTMENT_LEAD'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='greta') AND ROLES='DEPARTMENT_LEAD');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='hans'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='hans') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='iris'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='iris') AND ROLES='EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='iris'), 'MANAGEMENT'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='iris') AND ROLES='MANAGEMENT');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
SELECT (SELECT ID FROM USERX WHERE USERNAME='jonas'), 'EMPLOYEE'
WHERE NOT EXISTS (SELECT 1 FROM USERX_USERX_ROLE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='jonas') AND ROLES='EMPLOYEE');

-- Reassign department leads now that anna and greta exist
UPDATE DEPARTMENTS SET USERX_ID = (SELECT ID FROM USERX WHERE USERNAME='anna')  WHERE NAME='Engineering';
UPDATE DEPARTMENTS SET USERX_ID = (SELECT ID FROM USERX WHERE USERNAME='greta') WHERE NAME='HR';

-- =========================================
-- ROOMS
-- =========================================

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, TRUE, (SELECT ID FROM BUILDINGS WHERE NAME='Still OLD IT'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Research (2)'), 'Room 1', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Room 1');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Still OLD IT'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Research (2)'), 'Common Area 1', 'COMMON_AREAS'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Common Area 1');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Office A', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Eng Office A');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Office B', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Eng Office B');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Office C', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Eng Office C');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Common Area', 'COMMON_AREAS'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Eng Common Area');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'), 'HR Office A', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='HR Office A');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'), 'HR Office B', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='HR Office B');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'), 'HR Common Area', 'COMMON_AREAS'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='HR Common Area');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Mgmt Office A', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Mgmt Office A');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Mgmt Office B', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Mgmt Office B');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Mgmt Common Area', 'COMMON_AREAS'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Mgmt Common Area');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='South HQ'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Sales'), 'Sales Office A', 'OFFICE'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Sales Office A');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='South HQ'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Sales'), 'Sales Common Area', 'COMMON_AREAS'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Sales Common Area');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
SELECT TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Common Area 2', 'COMMON_AREAS'
WHERE NOT EXISTS (SELECT 1 FROM ROOMS WHERE NAME='Common Area 2');

-- =========================================
-- EMPLOYEE PROFILES
-- =========================================

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='admin'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Research (2)'), (SELECT ID FROM ROOMS WHERE NAME='Room 1')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='admin'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='user1'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Research (2)'), (SELECT ID FROM ROOMS WHERE NAME='Room 1')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='user1'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='user2'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Research (2)'), (SELECT ID FROM ROOMS WHERE NAME='Common Area 1')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='user2'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='elvis'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), (SELECT ID FROM ROOMS WHERE NAME='Common Area 2')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='elvis'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='anna'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office A')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='anna'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='ben'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office A')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='ben'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='clara'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office B')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='clara'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='david'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office B')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='david'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='eva'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'), (SELECT ID FROM ROOMS WHERE NAME='HR Office A')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='eva'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='felix'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'), (SELECT ID FROM ROOMS WHERE NAME='HR Office A')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='felix'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='greta'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'), (SELECT ID FROM ROOMS WHERE NAME='HR Office B')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='greta'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='hans'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='hans'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='iris'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='iris'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
SELECT (SELECT ID FROM USERX WHERE USERNAME='jonas'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office B')
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEEPROFILE WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='jonas'));

-- =========================================
-- ABSENCES
-- =========================================

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-22 19:11:35.668', TIMESTAMP '2026-04-22 19:11:35.668', (SELECT ID FROM USERX WHERE USERNAME='admin'), 'PLANNED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='admin') AND START_DATE=TIMESTAMP '2026-04-22 19:11:35.668' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-10 09:00:00', TIMESTAMP '2026-04-12 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='user1'), 'PLANNED', 'SICKNESS'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='user1') AND START_DATE=TIMESTAMP '2026-04-10 09:00:00' AND ABSENCE_TYPE='SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-10 09:00:00', TIMESTAMP '2026-04-12 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='elvis'), 'PLANNED', 'SICKNESS'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='elvis') AND START_DATE=TIMESTAMP '2026-04-10 09:00:00' AND ABSENCE_TYPE='SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-05 08:00:00', TIMESTAMP '2026-04-06 17:00:00', (SELECT ID FROM USERX WHERE USERNAME='admin'), 'PLANNED', 'SICKNESS'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='admin') AND START_DATE=TIMESTAMP '2026-04-05 08:00:00' AND ABSENCE_TYPE='SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-08 09:00:00', TIMESTAMP '2026-04-09 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='elvis'), 'PLANNED', 'PARENTAL_LEAVE'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='elvis') AND START_DATE=TIMESTAMP '2026-04-08 09:00:00' AND ABSENCE_TYPE='PARENTAL_LEAVE');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-01-15 08:00:00', TIMESTAMP '2026-01-17 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='anna'), 'APPROVED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='anna') AND START_DATE=TIMESTAMP '2026-01-15 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-02-03 08:00:00', TIMESTAMP '2026-02-04 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='ben'), 'APPROVED', 'SICKNESS'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='ben') AND START_DATE=TIMESTAMP '2026-02-03 08:00:00' AND ABSENCE_TYPE='SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-02-10 08:00:00', TIMESTAMP '2026-02-14 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='clara'), 'APPROVED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='clara') AND START_DATE=TIMESTAMP '2026-02-10 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-03-01 08:00:00', TIMESTAMP '2026-03-05 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='david'), 'APPROVED', 'PARENTAL_LEAVE'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='david') AND START_DATE=TIMESTAMP '2026-03-01 08:00:00' AND ABSENCE_TYPE='PARENTAL_LEAVE');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-03-20 08:00:00', TIMESTAMP '2026-03-21 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='eva'), 'PLANNED', 'SICKNESS'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='eva') AND START_DATE=TIMESTAMP '2026-03-20 08:00:00' AND ABSENCE_TYPE='SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-01 08:00:00', TIMESTAMP '2026-04-03 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='felix'), 'APPROVED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='felix') AND START_DATE=TIMESTAMP '2026-04-01 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-04-14 08:00:00', TIMESTAMP '2026-04-18 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='greta'), 'APPROVED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='greta') AND START_DATE=TIMESTAMP '2026-04-14 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-01-27 08:00:00', TIMESTAMP '2026-01-31 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='hans'), 'APPROVED', 'OTHER'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='hans') AND START_DATE=TIMESTAMP '2026-01-27 08:00:00' AND ABSENCE_TYPE='OTHER');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-02-24 08:00:00', TIMESTAMP '2026-02-26 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='iris'), 'APPROVED', 'SICKNESS'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='iris') AND START_DATE=TIMESTAMP '2026-02-24 08:00:00' AND ABSENCE_TYPE='SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-03-10 08:00:00', TIMESTAMP '2026-03-12 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='jonas'), 'APPROVED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='jonas') AND START_DATE=TIMESTAMP '2026-03-10 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-05-05 08:00:00', TIMESTAMP '2026-05-09 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='anna'), 'PLANNED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='anna') AND START_DATE=TIMESTAMP '2026-05-05 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
SELECT TIMESTAMP '2026-05-05 08:00:00', TIMESTAMP '2026-05-09 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='ben'), 'PLANNED', 'HOLIDAY'
WHERE NOT EXISTS (SELECT 1 FROM ABSENCES WHERE USERX_ID=(SELECT ID FROM USERX WHERE USERNAME='ben') AND START_DATE=TIMESTAMP '2026-05-05 08:00:00' AND ABSENCE_TYPE='HOLIDAY');

-- =========================================
-- CLIMATE HINTS
-- =========================================

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 1, 'Use a reverse-water-sprayer'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Use a reverse-water-sprayer');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 3, 'Open windows when temperature is high'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Open windows when temperature is high');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 1, 'Lower the blinds to reduce solar heat gain.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Lower the blinds to reduce solar heat gain.');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 1, 'Check if the heating system is set too high.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Check if the heating system is set too high.');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 0, 'Run the dehumidifier for 30 minutes.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Run the dehumidifier for 30 minutes.');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 0, 'Ensure windows are sealed properly.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Ensure windows are sealed properly.');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 3, 'Ventilate the room immediately by opening windows.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 3, 'Check if the air filter needs replacing.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Check if the air filter needs replacing.');

INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
SELECT 2, 'Barometric pressure anomaly — check HVAC settings.'
WHERE NOT EXISTS (SELECT 1 FROM CLIMATEHINTS WHERE HINT_TEXT='Barometric pressure anomaly — check HVAC settings.');

-- =========================================
-- RASPBERRY PIs
-- =========================================

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-room1', '192.168.1.10', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Room 1')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-room1');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-common1', '192.168.1.11', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-common1');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-eng-a', '192.168.2.10', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-a');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-eng-b', '192.168.2.11', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-b');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-eng-c', '192.168.2.12', 'OFFLINE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office C')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-c');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-eng-common', '192.168.2.13', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-common');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-hr-a', '192.168.3.10', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-a');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-hr-b', '192.168.3.11', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-b');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-hr-common', '192.168.3.12', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='HR Common Area')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-common');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-mgmt-a', '192.168.4.10', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-a');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-mgmt-b', '192.168.4.11', 'DEGRADED', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office B')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-b');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-mgmt-common', '192.168.4.12', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Common Area')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-common');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-sales-a', '192.168.5.10', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-sales-a');

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
SELECT 'rpi-sales-common', '192.168.5.11', 'ONLINE', (SELECT ID FROM ROOMS WHERE NAME='Sales Common Area')
WHERE NOT EXISTS (SELECT 1 FROM RASPBERRYPIS WHERE HOST_NAME='rpi-sales-common');

-- =========================================
-- SENSOR STATIONS
-- =========================================

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Station A', 'ONLINE', 1, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-room1'), (SELECT ID FROM ROOMS WHERE NAME='Room 1')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Station A');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Station B', 'ONLINE', 1, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-common1'), (SELECT ID FROM ROOMS WHERE NAME='Common Area 1')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Station B');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Eng-A-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-a'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office A')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Eng-A-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Eng-B-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-b'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office B')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Eng-B-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Eng-C-S1', 'CONNECTION_FAILED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-c'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office C')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Eng-C-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Eng-Common-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-common'), (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'HR-A-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-a'), (SELECT ID FROM ROOMS WHERE NAME='HR Office A')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='HR-A-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'HR-B-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-b'), (SELECT ID FROM ROOMS WHERE NAME='HR Office B')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='HR-B-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'HR-Common-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-common'), (SELECT ID FROM ROOMS WHERE NAME='HR Common Area')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='HR-Common-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Mgmt-A-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-a'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Mgmt-B-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-b'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office B')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Mgmt-B-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Mgmt-Common-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-common'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Common Area')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Mgmt-Common-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Sales-A-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-sales-a'), (SELECT ID FROM ROOMS WHERE NAME='Sales Office A')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Sales-A-S1');

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
SELECT 'Sales-Common-S1', 'CONNECTED', 2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-sales-common'), (SELECT ID FROM ROOMS WHERE NAME='Sales Common Area')
WHERE NOT EXISTS (SELECT 1 FROM SENSORSTATIONS WHERE NAME='Sales-Common-S1');

-- =========================================
-- THRESHOLDS
-- =========================================

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 60, (SELECT ID FROM ROOMS WHERE NAME='Room 1'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60);

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 27.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'TEMPERATURE', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 18.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'TEMPERATURE', 'LOWER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='LOWER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 65.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 400.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'IAQ', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 27.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), 'TEMPERATURE', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 65.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 400.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), 'IAQ', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 26.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), 'TEMPERATURE', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 60.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 350.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), 'IAQ', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 26.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), 'TEMPERATURE', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 60.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 25.0, (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), 'TEMPERATURE', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 55.0, (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT FALSE, 300.0, (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), 'IAQ', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 28.0, (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), 'TEMPERATURE', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 70.0, (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), 'HUMIDITY', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER');

INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
SELECT TRUE, 500.0, (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), 'IAQ', 'UPPER'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER');

-- =========================================
-- THRESHOLD → CLIMATE HINT LINKS
-- =========================================

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
SELECT (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Use a reverse-water-sprayer'),
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60)
WHERE NOT EXISTS (
    SELECT 1 FROM CLIMATEHINT_THRESHOLD
    WHERE CLIMATEHINT_ID=(SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Use a reverse-water-sprayer')
      AND THRESHOLD_ID=(SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60)
);

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
SELECT (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Open windows when temperature is high'),
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60)
WHERE NOT EXISTS (
    SELECT 1 FROM CLIMATEHINT_THRESHOLD
    WHERE CLIMATEHINT_ID=(SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Open windows when temperature is high')
      AND THRESHOLD_ID=(SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60)
);

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
SELECT (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Lower the blinds to reduce solar heat gain.'),
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER')
WHERE NOT EXISTS (
    SELECT 1 FROM CLIMATEHINT_THRESHOLD
    WHERE CLIMATEHINT_ID=(SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Lower the blinds to reduce solar heat gain.')
      AND THRESHOLD_ID=(SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER')
);

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
SELECT (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Run the dehumidifier for 30 minutes.'),
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER')
WHERE NOT EXISTS (
    SELECT 1 FROM CLIMATEHINT_THRESHOLD
    WHERE CLIMATEHINT_ID=(SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Run the dehumidifier for 30 minutes.')
      AND THRESHOLD_ID=(SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER')
);

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
SELECT (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.'),
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER')
WHERE NOT EXISTS (
    SELECT 1 FROM CLIMATEHINT_THRESHOLD
    WHERE CLIMATEHINT_ID=(SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.')
      AND THRESHOLD_ID=(SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER')
);

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
SELECT (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.'),
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER')
WHERE NOT EXISTS (
    SELECT 1 FROM CLIMATEHINT_THRESHOLD
    WHERE CLIMATEHINT_ID=(SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.')
      AND THRESHOLD_ID=(SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER')
);

-- =========================================
-- MEASUREMENTS
-- =========================================

-- Room 1 / Station A — spot measurements
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT TIMESTAMP '2026-04-23 08:00:00', 65, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=TIMESTAMP '2026-04-23 08:00:00' AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT TIMESTAMP '2026-04-23 08:00:00', 22, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=TIMESTAMP '2026-04-23 08:00:00' AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT TIMESTAMP '2026-04-23 08:00:00', 400, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=TIMESTAMP '2026-04-23 08:00:00' AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

-- Room 1 — TEMPERATURE series
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
FROM (VALUES
          (TIMESTAMP '2026-04-20 06:00:00', 19.0), (TIMESTAMP '2026-04-20 08:00:00', 21.0),
          (TIMESTAMP '2026-04-20 10:00:00', 23.0), (TIMESTAMP '2026-04-20 12:00:00', 25.0),
          (TIMESTAMP '2026-04-20 14:00:00', 26.0), (TIMESTAMP '2026-04-20 16:00:00', 24.0),
          (TIMESTAMP '2026-04-20 18:00:00', 22.0), (TIMESTAMP '2026-04-21 06:00:00', 20.0),
          (TIMESTAMP '2026-04-21 10:00:00', 24.0), (TIMESTAMP '2026-04-21 14:00:00', 27.0),
          (TIMESTAMP '2026-04-21 18:00:00', 23.0), (TIMESTAMP '2026-04-22 06:00:00', 21.0),
          (TIMESTAMP '2026-04-22 12:00:00', 26.0), (TIMESTAMP '2026-04-22 18:00:00', 23.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

-- Room 1 — HUMIDITY series
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
FROM (VALUES
          (TIMESTAMP '2026-04-20 06:00:00', 45.0), (TIMESTAMP '2026-04-20 12:00:00', 60.0),
          (TIMESTAMP '2026-04-20 14:00:00', 72.0), (TIMESTAMP '2026-04-21 12:00:00', 68.0),
          (TIMESTAMP '2026-04-22 12:00:00', 75.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

-- Room 1 — IAQ series
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
FROM (VALUES
          (TIMESTAMP '2026-04-20 08:00:00', 300.0), (TIMESTAMP '2026-04-20 12:00:00', 450.0),
          (TIMESTAMP '2026-04-20 16:00:00', 420.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

-- Room 1 — PRESSURE series
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')
FROM (VALUES
          (TIMESTAMP '2026-04-20 06:00:00', 1012.0), (TIMESTAMP '2026-04-20 12:00:00', 1010.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='PRESSURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1'));

-- Common Area 1 / Station B
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT TIMESTAMP '2026-04-23 08:00:00', 21, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B')
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=TIMESTAMP '2026-04-23 08:00:00' AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Common Area 1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B')
FROM (VALUES
          (TIMESTAMP '2026-04-20 06:00:00', 18.0), (TIMESTAMP '2026-04-20 12:00:00', 21.0),
          (TIMESTAMP '2026-04-20 18:00:00', 20.0), (TIMESTAMP '2026-04-21 06:00:00', 19.0),
          (TIMESTAMP '2026-04-21 12:00:00', 22.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Common Area 1'));

-- Eng Office A / Eng-A-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 20.1), (TIMESTAMP '2026-01-23 06:00:00', 21.4),
          (TIMESTAMP '2026-01-23 12:00:00', 23.7), (TIMESTAMP '2026-01-23 18:00:00', 22.5),
          (TIMESTAMP '2026-02-05 00:00:00', 19.8), (TIMESTAMP '2026-02-05 06:00:00', 21.0),
          (TIMESTAMP '2026-02-05 12:00:00', 24.2), (TIMESTAMP '2026-02-05 18:00:00', 22.9),
          (TIMESTAMP '2026-02-15 10:00:00', 27.6), (TIMESTAMP '2026-02-15 14:00:00', 28.4),
          (TIMESTAMP '2026-03-10 00:00:00', 20.5), (TIMESTAMP '2026-03-10 12:00:00', 23.1),
          (TIMESTAMP '2026-04-01 00:00:00', 21.2), (TIMESTAMP '2026-04-01 12:00:00', 24.8),
          (TIMESTAMP '2026-04-22 00:00:00', 21.9), (TIMESTAMP '2026-04-22 12:00:00', 25.3)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 52.0), (TIMESTAMP '2026-01-23 06:00:00', 55.3),
          (TIMESTAMP '2026-01-23 12:00:00', 60.1), (TIMESTAMP '2026-01-23 18:00:00', 57.4),
          (TIMESTAMP '2026-02-05 12:00:00', 62.8), (TIMESTAMP '2026-03-08 09:00:00', 66.4),
          (TIMESTAMP '2026-03-08 15:00:00', 69.1), (TIMESTAMP '2026-04-01 12:00:00', 58.7),
          (TIMESTAMP '2026-04-22 12:00:00', 61.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 06:00:00', 280.0), (TIMESTAMP '2026-01-23 12:00:00', 340.0),
          (TIMESTAMP '2026-01-23 18:00:00', 310.0), (TIMESTAMP '2026-02-05 12:00:00', 370.0),
          (TIMESTAMP '2026-03-10 12:00:00', 390.0), (TIMESTAMP '2026-04-22 14:00:00', 431.0),
          (TIMESTAMP '2026-04-22 18:00:00', 415.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 1011.5), (TIMESTAMP '2026-02-05 00:00:00', 1012.0),
          (TIMESTAMP '2026-03-10 00:00:00', 1010.3), (TIMESTAMP '2026-04-22 00:00:00', 1013.1)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='PRESSURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

-- Eng Office B / Eng-B-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 21.5), (TIMESTAMP '2026-01-23 12:00:00', 24.8),
          (TIMESTAMP '2026-02-10 12:00:00', 25.9), (TIMESTAMP '2026-03-20 12:00:00', 27.8),
          (TIMESTAMP '2026-03-20 18:00:00', 26.1), (TIMESTAMP '2026-04-22 12:00:00', 25.4)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 58.0), (TIMESTAMP '2026-01-23 12:00:00', 64.5),
          (TIMESTAMP '2026-02-10 12:00:00', 67.2), (TIMESTAMP '2026-04-21 08:00:00', 72.3),
          (TIMESTAMP '2026-04-22 12:00:00', 70.8)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 12:00:00', 295.0), (TIMESTAMP '2026-02-10 12:00:00', 360.0),
          (TIMESTAMP '2026-04-22 12:00:00', 385.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 1010.0), (TIMESTAMP '2026-03-10 00:00:00', 1011.5),
          (TIMESTAMP '2026-04-22 00:00:00', 1012.2)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='PRESSURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

-- HR Office A / HR-A-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 19.5), (TIMESTAMP '2026-01-23 12:00:00', 22.0),
          (TIMESTAMP '2026-02-15 12:00:00', 23.4), (TIMESTAMP '2026-03-10 12:00:00', 22.8),
          (TIMESTAMP '2026-04-22 12:00:00', 24.1)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 45.0), (TIMESTAMP '2026-01-23 12:00:00', 50.5),
          (TIMESTAMP '2026-02-15 12:00:00', 54.0), (TIMESTAMP '2026-04-23 06:00:00', 63.5),
          (TIMESTAMP '2026-04-23 12:00:00', 61.2)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 12:00:00', 265.0), (TIMESTAMP '2026-01-30 13:00:00', 348.0),
          (TIMESTAMP '2026-01-30 17:00:00', 362.0), (TIMESTAMP '2026-03-10 12:00:00', 290.0),
          (TIMESTAMP '2026-04-22 12:00:00', 310.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 1012.0), (TIMESTAMP '2026-03-10 00:00:00', 1011.0),
          (TIMESTAMP '2026-04-22 00:00:00', 1013.5)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='PRESSURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

-- HR Office B / HR-B-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 20.5), (TIMESTAMP '2026-01-23 12:00:00', 22.8),
          (TIMESTAMP '2026-02-20 14:00:00', 26.5), (TIMESTAMP '2026-02-20 18:00:00', 27.1),
          (TIMESTAMP '2026-03-15 11:00:00', 25.8), (TIMESTAMP '2026-03-15 15:00:00', 26.9),
          (TIMESTAMP '2026-04-22 12:00:00', 24.3)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 49.0), (TIMESTAMP '2026-01-23 12:00:00', 54.5),
          (TIMESTAMP '2026-02-20 12:00:00', 57.0), (TIMESTAMP '2026-04-22 12:00:00', 55.3)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B'));

-- Mgmt Office A / Mgmt-A-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 21.0), (TIMESTAMP '2026-01-23 12:00:00', 22.5),
          (TIMESTAMP '2026-02-15 12:00:00', 23.0), (TIMESTAMP '2026-03-01 09:00:00', 24.8),
          (TIMESTAMP '2026-03-01 12:00:00', 25.6), (TIMESTAMP '2026-04-22 12:00:00', 23.2)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 43.0), (TIMESTAMP '2026-01-23 12:00:00', 48.0),
          (TIMESTAMP '2026-03-10 12:00:00', 50.5), (TIMESTAMP '2026-04-22 12:00:00', 47.2)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 12:00:00', 245.0), (TIMESTAMP '2026-03-10 12:00:00', 270.0),
          (TIMESTAMP '2026-04-22 12:00:00', 260.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 1013.0), (TIMESTAMP '2026-03-10 00:00:00', 1012.5),
          (TIMESTAMP '2026-04-22 00:00:00', 1014.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='PRESSURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

-- Sales Office A / Sales-A-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 23.0), (TIMESTAMP '2026-01-23 12:00:00', 26.5),
          (TIMESTAMP '2026-02-10 12:00:00', 27.4), (TIMESTAMP '2026-03-15 12:00:00', 28.1),
          (TIMESTAMP '2026-04-22 12:00:00', 29.2), (TIMESTAMP '2026-04-22 18:00:00', 28.7)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 60.0), (TIMESTAMP '2026-01-23 12:00:00', 68.0),
          (TIMESTAMP '2026-02-10 12:00:00', 71.5), (TIMESTAMP '2026-04-22 12:00:00', 73.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='HUMIDITY' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 12:00:00', 390.0), (TIMESTAMP '2026-01-25 12:00:00', 512.0),
          (TIMESTAMP '2026-02-28 13:00:00', 480.0), (TIMESTAMP '2026-02-28 17:00:00', 498.0),
          (TIMESTAMP '2026-04-22 12:00:00', 430.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 1009.5), (TIMESTAMP '2026-03-10 00:00:00', 1010.5),
          (TIMESTAMP '2026-04-22 00:00:00', 1008.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='PRESSURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A'));

-- Eng Common Area / Eng-Common-S1
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 00:00:00', 19.5), (TIMESTAMP '2026-01-23 12:00:00', 21.0),
          (TIMESTAMP '2026-02-15 12:00:00', 21.8), (TIMESTAMP '2026-03-10 12:00:00', 20.5),
          (TIMESTAMP '2026-04-22 12:00:00', 22.1)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='TEMPERATURE' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
SELECT ts, val, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')
FROM (VALUES
          (TIMESTAMP '2026-01-23 06:00:00', 295.0), (TIMESTAMP '2026-01-23 12:00:00', 370.0),
          (TIMESTAMP '2026-02-15 12:00:00', 400.0), (TIMESTAMP '2026-03-10 12:00:00', 340.0),
          (TIMESTAMP '2026-04-22 12:00:00', 380.0)
     ) AS v(ts, val)
WHERE NOT EXISTS (SELECT 1 FROM MEASUREMENT WHERE TIMESTAMP=v.ts AND METRIC='IAQ' AND ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'));

-- =========================================
-- THRESHOLD VIOLATIONS
-- =========================================

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-04-13 11:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='Room 1'),
       TIMESTAMP '2026-04-13 10:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60),
       28, 'TEMPERATURE', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND START_TIME=TIMESTAMP '2026-04-13 10:00:00' AND METRIC='TEMPERATURE');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT NULL,
       (SELECT ID FROM ROOMS WHERE NAME='Room 1'),
       TIMESTAMP '2026-04-23 07:45:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER' AND BOUND_VALUE=60),
       65, 'HUMIDITY', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Room 1') AND START_TIME=TIMESTAMP '2026-04-23 07:45:00' AND METRIC='HUMIDITY');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-02-15 16:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'),
       TIMESTAMP '2026-02-15 11:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
       28.4, 'TEMPERATURE', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND START_TIME=TIMESTAMP '2026-02-15 11:00:00' AND METRIC='TEMPERATURE');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-03-08 15:30:00',
       (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'),
       TIMESTAMP '2026-03-08 09:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER'),
       69.1, 'HUMIDITY', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND START_TIME=TIMESTAMP '2026-03-08 09:00:00' AND METRIC='HUMIDITY');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT NULL,
       (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'),
       TIMESTAMP '2026-04-22 14:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
       431.0, 'IAQ', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND START_TIME=TIMESTAMP '2026-04-22 14:00:00' AND METRIC='IAQ');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT NULL,
       (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'),
       TIMESTAMP '2026-04-21 08:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER'),
       72.3, 'HUMIDITY', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND START_TIME=TIMESTAMP '2026-04-21 08:00:00' AND METRIC='HUMIDITY');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-03-20 18:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'),
       TIMESTAMP '2026-03-20 12:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
       27.8, 'TEMPERATURE', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND START_TIME=TIMESTAMP '2026-03-20 12:00:00' AND METRIC='TEMPERATURE');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-01-30 17:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='HR Office A'),
       TIMESTAMP '2026-01-30 13:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
       362.0, 'IAQ', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND START_TIME=TIMESTAMP '2026-01-30 13:00:00' AND METRIC='IAQ');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT NULL,
       (SELECT ID FROM ROOMS WHERE NAME='HR Office A'),
       TIMESTAMP '2026-04-23 06:30:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER'),
       63.5, 'HUMIDITY', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND START_TIME=TIMESTAMP '2026-04-23 06:30:00' AND METRIC='HUMIDITY');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-02-20 19:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='HR Office B'),
       TIMESTAMP '2026-02-20 14:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
       27.1, 'TEMPERATURE', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND START_TIME=TIMESTAMP '2026-02-20 14:00:00' AND METRIC='TEMPERATURE');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-03-15 16:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='HR Office B'),
       TIMESTAMP '2026-03-15 11:30:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
       26.9, 'TEMPERATURE', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND START_TIME=TIMESTAMP '2026-03-15 11:30:00' AND METRIC='TEMPERATURE');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-03-01 12:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'),
       TIMESTAMP '2026-03-01 09:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
       25.6, 'TEMPERATURE', 'DISABLED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A') AND START_TIME=TIMESTAMP '2026-03-01 09:00:00' AND METRIC='TEMPERATURE');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-01-25 18:00:00',
       (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'),
       TIMESTAMP '2026-01-25 12:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
       512.0, 'IAQ', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND START_TIME=TIMESTAMP '2026-01-25 12:00:00' AND METRIC='IAQ');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT TIMESTAMP '2026-02-28 17:30:00',
       (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'),
       TIMESTAMP '2026-02-28 13:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
       498.0, 'IAQ', 'RESOLVED'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND START_TIME=TIMESTAMP '2026-02-28 13:00:00' AND METRIC='IAQ');

INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
SELECT NULL,
       (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'),
       TIMESTAMP '2026-04-22 12:00:00',
       (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
       29.2, 'TEMPERATURE', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM THRESHOLDVIOLATIONS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND START_TIME=TIMESTAMP '2026-04-22 12:00:00' AND METRIC='TEMPERATURE');