-- noinspection SqlNoDataSourceInspectionForFile

-- Drop the not null constraint (you can use ALTER TABLE depending on your database)
ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID DROP NOT NULL;

-- Insert users into USERX table
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Admin', 'Istrator', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'admin', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Susi', 'Kaufgern', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user1', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Max', 'Mustermann', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'user2', NULL, '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Elvis', 'The King', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'elvis', NULL, '2024-01-01 00:00:00');

-- Insert roles into USERX_USERX_ROLE table by looking up the corresponding user ID
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'SYSTEM_ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGEMENT');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'SYSTEM_ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES)
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'EMPLOYEE');

-- Update CREATE_USER_ID fields after the initial insert
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'admin';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user1';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'admin') WHERE USERNAME = 'user2';
UPDATE USERX SET CREATE_USER_ID = (SELECT ID FROM USERX WHERE USERNAME = 'elvis') WHERE USERNAME = 'elvis';

-- Add the not null constraint back
ALTER TABLE USERX ALTER COLUMN CREATE_USER_ID SET NOT NULL;

-- ---------------------------------------------------------------------------
-- Extended test data based on SWE Postman create/patch payloads
-- Inserted in dependency order and using final patched state where applicable.
-- ---------------------------------------------------------------------------

-- Address (create + patch)
INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
VALUES ('Italy', '4999', 'Something', 'N/A', '81/A', 'Primary Address');

-- Building (create + patch)
INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
VALUES (
           'Still OLD IT',
           (SELECT ID FROM ADDRESSES
            WHERE COUNTRY = 'Italy'
              AND ZIP_CODE = '4999'
              AND CITY = 'Something'
              AND STREET = 'N/A'
              AND HOUSE_NUMBER = '81/A'
              AND EXTRA = 'Primary Address')
       );

-- Department (create + patch), departmentLeadId/userxId = 1 -> admin
INSERT INTO DEPARTMENTS (NAME, USERX_ID)
VALUES (
           'Research (2)',
           (SELECT ID FROM USERX WHERE USERNAME = 'admin')
       );

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
VALUES (
           'Sales',
           (SELECT ID FROM USERX WHERE USERNAME = 'elvis')
       );

-- Room (create only; the "Update room" request in Postman actually targets /building/1)
INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (
           TRUE,
           1,
           (SELECT ID FROM BUILDINGS WHERE NAME = 'Still OLD IT'),
           (SELECT ID FROM DEPARTMENTS WHERE NAME = 'Research (2)'),
           'Room 1',
           'OFFICE'
       );

-- EmployeeProfile (create; patch body is empty)
INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES (
           (SELECT ID FROM USERX WHERE USERNAME = 'admin'),
           (SELECT ID FROM DEPARTMENTS WHERE NAME = 'Research (2)'),
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1')
       );

-- Absence (create + patch)
INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (
           TIMESTAMP '2026-04-22 19:11:35.668',
           TIMESTAMP '2026-04-22 19:11:35.668',
           (SELECT ID FROM USERX WHERE USERNAME = 'admin'),
           'PLANNED',
           'HOLIDAY'
       );

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (
           TIMESTAMP '2026-04-10 09:00:00',
           TIMESTAMP '2026-04-12 18:00:00',
           (SELECT ID FROM USERX WHERE USERNAME = 'user1'),
           'PLANNED',
           'SICKNESS'
       );

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (
           TIMESTAMP '2026-04-10 09:00:00',
           TIMESTAMP '2026-04-12 18:00:00',
           (SELECT ID FROM USERX WHERE USERNAME = 'elvis'),
           'PLANNED',
           'SICKNESS'
       );

-- user1 in Research (2)
INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (
           TIMESTAMP '2026-04-05 08:00:00',
           TIMESTAMP '2026-04-06 17:00:00',
           (SELECT ID FROM USERX WHERE USERNAME = 'admin'),
           'PLANNED',
           'SICKNESS'
       );

-- evlis in Management
INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (
           TIMESTAMP '2026-04-08 09:00:00',
           TIMESTAMP '2026-04-09 18:00:00',
           (SELECT ID FROM USERX WHERE USERNAME = 'elvis'),
           'PLANNED',
           'PARENTAL_LEAVE'
       );


-- ClimateHint (create + patch)
-- Metric is stored as ordinal tinyint in this table. Based on the Metric enum
-- ordering used elsewhere (IAQ, HUMIDITY, PRESSURE, TEMPERATURE), HUMIDITY = 1.
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
VALUES (1, 'Use a reverse-water-sprayer');

-- Supporting second hint because the threshold payload references climateHintIds [1, 2]
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT)
VALUES (3, 'Open windows when temperature is high');

-- Threshold (create + patch)
-- Postman uses thresholdType = MAX, but the database enum is LOWER/UPPER, so MAX -> UPPER.
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (
           TRUE,
           60,
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1'),
           'HUMIDITY',
           'UPPER'
       );

-- Threshold to ClimateHint links
INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
VALUES (
           (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT = 'Use a reverse-water-sprayer'),
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID = (SELECT ID FROM ROOMS WHERE NAME = 'Room 1') AND METRIC = 'HUMIDITY' AND BOUND_VALUE = 60)
       );

INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
VALUES (
           (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT = 'Open windows when temperature is high'),
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID = (SELECT ID FROM ROOMS WHERE NAME = 'Room 1') AND METRIC = 'HUMIDITY' AND BOUND_VALUE = 60)
       );

-- ThresholdViolation (create + patch)
INSERT INTO THRESHOLDVIOLATIONS (
    END_TIME,
    ROOM_ID,
    START_TIME,
    THRESHOLD_ID,
    "value",
    METRIC,
    VIOLATION_STATUS
) VALUES (
             TIMESTAMP '2026-04-13 11:00:00',
             (SELECT ID FROM ROOMS WHERE NAME = 'Room 1'),
             TIMESTAMP '2026-04-13 10:00:00',
             (SELECT ID FROM THRESHOLDS
              WHERE ROOM_ID = (SELECT ID FROM ROOMS WHERE NAME = 'Room 1')
                AND METRIC = 'HUMIDITY'
                AND BOUND_VALUE = 60),
             28,
             'TEMPERATURE',
             'RESOLVED'
         );


-- Common-areas room (same building + department as Room 1)
INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (
           TRUE,
           FALSE,
           (SELECT ID FROM BUILDINGS WHERE NAME = 'Still OLD IT'),
           (SELECT ID FROM DEPARTMENTS WHERE NAME = 'Research (2)'),
           'Common Area 1',
           'COMMON_AREAS'
       );

-- EmployeeProfiles for user1 and user2
--    Assumes users with USERNAME = 'user1' and 'user2' exist in USERX.
INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES (
           (SELECT ID FROM USERX WHERE USERNAME = 'user1'),
           (SELECT ID FROM DEPARTMENTS WHERE NAME = 'Research (2)'),
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1')
       );

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES (
           (SELECT ID FROM USERX WHERE USERNAME = 'user2'),
           (SELECT ID FROM DEPARTMENTS WHERE NAME = 'Research (2)'),
           (SELECT ID FROM ROOMS WHERE NAME = 'Common Area 1')
       );

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES (
           (SELECT ID FROM USERX WHERE USERNAME = 'elvis'),
           (SELECT ID FROM DEPARTMENTS WHERE NAME = 'Management'),
           (SELECT ID FROM ROOMS WHERE NAME = 'Common Area 2')
       );

-- RaspberryPi + SensorStation needed as FK for Measurements
INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES (
           'rpi-room1',
           '192.168.1.10',
           'ONLINE',
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1')
       );

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES (
           'Station A',
           'ONLINE',
           1.0,
           (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME = 'rpi-room1'),
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1')
       );

-- Measurements for Room 1 (gives Room Cards actual data to display)
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
VALUES (
           TIMESTAMP '2026-04-23 08:00:00',
           65,
           'HUMIDITY',
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1'),
           (SELECT ID FROM SENSORSTATIONS WHERE NAME = 'Station A')
       );

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
VALUES (
           TIMESTAMP '2026-04-23 08:00:00',
           22,
           'TEMPERATURE',
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1'),
           (SELECT ID FROM SENSORSTATIONS WHERE NAME = 'Station A')
       );

-- Active ThresholdViolation (triggers the warning badge on Room Cards)
--    Re-uses the existing HUMIDITY threshold on Room 1.
INSERT INTO THRESHOLDVIOLATIONS (
    END_TIME,
    ROOM_ID,
    START_TIME,
    THRESHOLD_ID,
    "value",
    METRIC,
    VIOLATION_STATUS
) VALUES (
             NULL,
             (SELECT ID FROM ROOMS WHERE NAME = 'Room 1'),
             TIMESTAMP '2026-04-23 07:45:00',
             (SELECT ID FROM THRESHOLDS
              WHERE ROOM_ID = (SELECT ID FROM ROOMS WHERE NAME = 'Room 1')
                AND METRIC = 'HUMIDITY'
                AND BOUND_VALUE = 60),
             65,
             'HUMIDITY',
             'ACTIVE'
         );

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
VALUES (
           TIMESTAMP '2026-04-23 08:00:00',
           400,
           'IAQ',
           (SELECT ID FROM ROOMS WHERE NAME = 'Room 1'),
           (SELECT ID FROM SENSORSTATIONS WHERE NAME = 'Station A')
       );

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES (
           'rpi-common1',
           '192.168.1.11',
           'ONLINE',
           (SELECT ID FROM ROOMS WHERE NAME = 'Common Area 1')
       );

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES (
           'Station B',
           'ONLINE',
           1.0,
           (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME = 'rpi-common1'),
           (SELECT ID FROM ROOMS WHERE NAME = 'Common Area 1')
       );

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID)
VALUES (
           TIMESTAMP '2026-04-23 08:00:00',
           21,
           'TEMPERATURE',
           (SELECT ID FROM ROOMS WHERE NAME = 'Common Area 1'),
           (SELECT ID FROM SENSORSTATIONS WHERE NAME = 'Station B')
       );

-- -------------------------------
-- ROOM 1 (Station A)
-- -------------------------------

-- TEMPERATURE (3 days)
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-04-20 06:00:00', 19.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 08:00:00', 21.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 10:00:00', 23.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 12:00:00', 25.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 14:00:00', 26.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 16:00:00', 24.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 18:00:00', 22.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),

                                                                                        (TIMESTAMP '2026-04-21 06:00:00', 20.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-21 10:00:00', 24.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-21 14:00:00', 27.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-21 18:00:00', 23.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),

                                                                                        (TIMESTAMP '2026-04-22 06:00:00', 21.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 26.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-22 18:00:00', 23.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A'));

-- HUMIDITY
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-04-20 06:00:00', 45.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 12:00:00', 60.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 14:00:00', 72.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-21 12:00:00', 68.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 75.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A'));

-- IAQ
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-04-20 08:00:00', 300.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 12:00:00', 450.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 16:00:00', 420.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A'));

-- PRESSURE
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-04-20 06:00:00', 1012.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A')),
                                                                                        (TIMESTAMP '2026-04-20 12:00:00', 1010.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Room 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station A'));

-- -------------------------------
-- COMMON AREA 1 (Station B)
-- -------------------------------

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-04-20 06:00:00', 18.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B')),
                                                                                        (TIMESTAMP '2026-04-20 12:00:00', 21.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B')),
                                                                                        (TIMESTAMP '2026-04-20 18:00:00', 20.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B')),

                                                                                        (TIMESTAMP '2026-04-21 06:00:00', 19.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B')),
                                                                                        (TIMESTAMP '2026-04-21 12:00:00', 22.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Common Area 1'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Station B'));




-- =============================================================================
-- EXTENDED DUMMY DATA — ClimateCanary (H2-compatible, no recursive CTEs)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- ADDRESSES
-- -----------------------------------------------------------------------------
INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
VALUES ('Austria', '6020', 'Innsbruck', 'Technikerstraße', '21', 'Campus West');

INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
VALUES ('Austria', '6020', 'Innsbruck', 'Innrain', '52', 'Main Campus');

INSERT INTO ADDRESSES (COUNTRY, ZIP_CODE, CITY, STREET, HOUSE_NUMBER, EXTRA)
VALUES ('Germany', '80333', 'Munich', 'Maximilianstraße', '4', 'HQ South');


-- -----------------------------------------------------------------------------
-- BUILDINGS
-- -----------------------------------------------------------------------------
INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
VALUES ('Tech Tower', (SELECT ID FROM ADDRESSES WHERE CITY = 'Innsbruck' AND STREET = 'Technikerstraße'));

INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
VALUES ('Main Office', (SELECT ID FROM ADDRESSES WHERE CITY = 'Innsbruck' AND STREET = 'Innrain'));

INSERT INTO BUILDINGS (NAME, ADDRESS_ID)
VALUES ('South HQ', (SELECT ID FROM ADDRESSES WHERE CITY = 'Munich'));


-- -----------------------------------------------------------------------------
-- DEPARTMENTS
-- -----------------------------------------------------------------------------
INSERT INTO DEPARTMENTS (NAME, USERX_ID)
VALUES ('Engineering', (SELECT ID FROM USERX WHERE USERNAME = 'admin'));

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
VALUES ('HR', (SELECT ID FROM USERX WHERE USERNAME = 'admin'));

INSERT INTO DEPARTMENTS (NAME, USERX_ID)
VALUES ('Management', (SELECT ID FROM USERX WHERE USERNAME = 'user1'));


-- -----------------------------------------------------------------------------
-- USERS
-- -----------------------------------------------------------------------------
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Anna',  'Berger',   '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'anna',  (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Ben',   'Schmidt',  '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'ben',   (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Clara', 'Huber',    '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'clara', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'David', 'Müller',   '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'david', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Eva',   'Kowalski', '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'eva',   (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Felix', 'Wagner',   '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'felix', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Greta', 'Fischer',  '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'greta', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Hans',  'Bauer',    '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'hans',  (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Iris',  'Klein',    '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'iris',  (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE)
VALUES (TRUE, 'Jonas', 'Wolf',     '{bcrypt}$2b$12$gimw81jnsxtcHMBRe6LVe.NZCPf3G2ugUyKqcYwJRlJuN6ubTXkNS', 'jonas', (SELECT ID FROM USERX WHERE USERNAME='admin'), '2024-01-01 00:00:00');

-- Roles
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='anna'),  'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='anna'),  'DEPARTMENT_LEAD');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='ben'),   'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='clara'), 'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='david'), 'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='eva'),   'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='eva'),   'BUILDING_ADMIN');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='felix'), 'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='greta'), 'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='greta'), 'DEPARTMENT_LEAD');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='hans'),  'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='iris'),  'EMPLOYEE');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='iris'),  'MANAGEMENT');
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) VALUES ((SELECT ID FROM USERX WHERE USERNAME='jonas'), 'EMPLOYEE');

UPDATE DEPARTMENTS SET USERX_ID = (SELECT ID FROM USERX WHERE USERNAME='anna')  WHERE NAME = 'Engineering';
UPDATE DEPARTMENTS SET USERX_ID = (SELECT ID FROM USERX WHERE USERNAME='greta') WHERE NAME = 'HR';


-- -----------------------------------------------------------------------------
-- ROOMS
-- -----------------------------------------------------------------------------
INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Office A',    'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Office B',    'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Office C',    'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Tech Tower'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), 'Eng Common Area', 'COMMON_AREAS');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'),          'HR Office A',     'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'),          'HR Office B',     'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'),          'HR Common Area',  'COMMON_AREAS');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Mgmt Office A',   'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Mgmt Office B',   'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Mgmt Common Area','COMMON_AREAS');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='South HQ'),   (SELECT ID FROM DEPARTMENTS WHERE NAME='Sales'),      'Sales Office A',  'OFFICE');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='South HQ'),   (SELECT ID FROM DEPARTMENTS WHERE NAME='Sales'),      'Sales Common Area','COMMON_AREAS');

INSERT INTO ROOMS (ACTIVE, PRIVACY_MODE, BUILDING_ID, DEPARTMENT_ID, NAME, ROOM_TYPE)
VALUES (TRUE, FALSE, (SELECT ID FROM BUILDINGS WHERE NAME='Main Office'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'), 'Common Area 2',   'COMMON_AREAS');


-- -----------------------------------------------------------------------------
-- EMPLOYEE PROFILES
-- -----------------------------------------------------------------------------
INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='anna'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='ben'),   (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='clara'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='david'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Engineering'), (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='eva'),   (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'),          (SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='felix'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'),          (SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='greta'), (SELECT ID FROM DEPARTMENTS WHERE NAME='HR'),          (SELECT ID FROM ROOMS WHERE NAME='HR Office B'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='hans'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'),  (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='iris'),  (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'),  (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO EMPLOYEEPROFILE (USERX_ID, DEPARTMENT_ID, ROOM_ID)
VALUES ((SELECT ID FROM USERX WHERE USERNAME='jonas'), (SELECT ID FROM DEPARTMENTS WHERE NAME='Management'),  (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office B'));

UPDATE EMPLOYEEPROFILE
SET ROOM_ID      = (SELECT ID FROM ROOMS       WHERE NAME='Common Area 2'),
    DEPARTMENT_ID = (SELECT ID FROM DEPARTMENTS WHERE NAME='Management')
WHERE USERX_ID = (SELECT ID FROM USERX WHERE USERNAME='elvis')
  AND DEPARTMENT_ID = (SELECT ID FROM DEPARTMENTS WHERE NAME='Management');


-- -----------------------------------------------------------------------------
-- ABSENCES
-- -----------------------------------------------------------------------------
INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-01-15 08:00:00', TIMESTAMP '2026-01-17 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='anna'),  'APPROVED', 'HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-02-03 08:00:00', TIMESTAMP '2026-02-04 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='ben'),   'APPROVED', 'SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-02-10 08:00:00', TIMESTAMP '2026-02-14 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='clara'), 'APPROVED', 'HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-03-01 08:00:00', TIMESTAMP '2026-03-05 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='david'), 'APPROVED', 'PARENTAL_LEAVE');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-03-20 08:00:00', TIMESTAMP '2026-03-21 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='eva'),   'PLANNED',  'SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-04-01 08:00:00', TIMESTAMP '2026-04-03 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='felix'), 'APPROVED', 'HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-04-14 08:00:00', TIMESTAMP '2026-04-18 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='greta'), 'APPROVED', 'HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-01-27 08:00:00', TIMESTAMP '2026-01-31 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='hans'),  'APPROVED', 'OTHER');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-02-24 08:00:00', TIMESTAMP '2026-02-26 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='iris'),  'APPROVED', 'SICKNESS');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-03-10 08:00:00', TIMESTAMP '2026-03-12 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='jonas'), 'APPROVED', 'HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-05-05 08:00:00', TIMESTAMP '2026-05-09 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='anna'),  'PLANNED',  'HOLIDAY');

INSERT INTO ABSENCES (START_DATE, END_DATE, USERX_ID, ABSENCE_STATUS, ABSENCE_TYPE)
VALUES (TIMESTAMP '2026-05-05 08:00:00', TIMESTAMP '2026-05-09 18:00:00', (SELECT ID FROM USERX WHERE USERNAME='ben'),   'PLANNED',  'HOLIDAY');


-- -----------------------------------------------------------------------------
-- CLIMATE HINTS
-- -----------------------------------------------------------------------------
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (1, 'Lower the blinds to reduce solar heat gain.');
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (1, 'Check if the heating system is set too high.');
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (0,    'Run the dehumidifier for 30 minutes.');
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (0,    'Ensure windows are sealed properly.');
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (3,         'Ventilate the room immediately by opening windows.');
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (3,         'Check if the air filter needs replacing.');
INSERT INTO CLIMATEHINTS (METRIC, HINT_TEXT) VALUES (2,    'Barometric pressure anomaly — check HVAC settings.');


-- -----------------------------------------------------------------------------
-- RASPBERRY PIs
-- -----------------------------------------------------------------------------
INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-eng-a',      '192.168.2.10', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-eng-b',      '192.168.2.11', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-eng-c',      '192.168.2.12', 'OFFLINE',  (SELECT ID FROM ROOMS WHERE NAME='Eng Office C'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-eng-common', '192.168.2.13', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-hr-a',       '192.168.3.10', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-hr-b',       '192.168.3.11', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='HR Office B'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-hr-common',  '192.168.3.12', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='HR Common Area'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-mgmt-a',     '192.168.4.10', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-mgmt-b',     '192.168.4.11', 'DEGRADED', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office B'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-mgmt-common','192.168.4.12', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Mgmt Common Area'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-sales-a',    '192.168.5.10', 'ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'));

INSERT INTO RASPBERRYPIS (HOST_NAME, IP_ADDRESS, DEVICE_STATUS, ROOM_ID)
VALUES ('rpi-sales-common','192.168.5.11','ONLINE',   (SELECT ID FROM ROOMS WHERE NAME='Sales Common Area'));


-- -----------------------------------------------------------------------------
-- SENSOR STATIONS
-- -----------------------------------------------------------------------------
INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Eng-A-S1',      'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-a'),       (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Eng-B-S1',      'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-b'),       (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Eng-C-S1',      'CONNECTION_FAILED',2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-c'),       (SELECT ID FROM ROOMS WHERE NAME='Eng Office C'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Eng-Common-S1', 'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-eng-common'),  (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('HR-A-S1',       'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-a'),        (SELECT ID FROM ROOMS WHERE NAME='HR Office A'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('HR-B-S1',       'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-b'),        (SELECT ID FROM ROOMS WHERE NAME='HR Office B'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('HR-Common-S1',  'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-hr-common'),   (SELECT ID FROM ROOMS WHERE NAME='HR Common Area'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Mgmt-A-S1',     'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-a'),      (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Mgmt-B-S1',     'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-b'),      (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office B'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Mgmt-Common-S1','CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-mgmt-common'), (SELECT ID FROM ROOMS WHERE NAME='Mgmt Common Area'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Sales-A-S1',    'CONNECTED',        2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-sales-a'),     (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'));

INSERT INTO SENSORSTATIONS (NAME, DEVICE_STATUS, MEASUREMENT_INTERVAL, RASPBERRY_PI_ID, ROOM_ID)
VALUES ('Sales-Common-S1','CONNECTED',       2, (SELECT ID FROM RASPBERRYPIS WHERE HOST_NAME='rpi-sales-common'),(SELECT ID FROM ROOMS WHERE NAME='Sales Common Area'));


-- -----------------------------------------------------------------------------
-- THRESHOLDS
-- -----------------------------------------------------------------------------
-- Eng Office A
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  27.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'TEMPERATURE', 'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  18.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'TEMPERATURE', 'LOWER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  65.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'HUMIDITY',    'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE, 400.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), 'IAQ',         'UPPER');

-- Eng Office B
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  27.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), 'TEMPERATURE', 'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  65.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), 'HUMIDITY',    'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE, 400.0, (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), 'IAQ',         'UPPER');

-- HR Office A
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  26.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), 'TEMPERATURE', 'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  60.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), 'HUMIDITY',    'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE, 350.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), 'IAQ',         'UPPER');

-- HR Office B
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE, 26.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), 'TEMPERATURE', 'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE, 60.0, (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), 'HUMIDITY',    'UPPER');

-- Mgmt Office A
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,   25.0, (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), 'TEMPERATURE', 'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,   55.0, (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), 'HUMIDITY',    'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (FALSE, 300.0, (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), 'IAQ',         'UPPER');

-- Sales Office A
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  28.0, (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), 'TEMPERATURE', 'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE,  70.0, (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), 'HUMIDITY',    'UPPER');
INSERT INTO THRESHOLDS (ENABLED, BOUND_VALUE, ROOM_ID, METRIC, THRESHOLD_TYPE)
VALUES (TRUE, 500.0, (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), 'IAQ',         'UPPER');

-- Threshold → ClimateHint links
INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
VALUES (
           (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Lower the blinds to reduce solar heat gain.'),
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER')
       );
INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
VALUES (
           (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Run the dehumidifier for 30 minutes.'),
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER')
       );
INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
VALUES (
           (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.'),
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER')
       );
INSERT INTO CLIMATEHINT_THRESHOLD (CLIMATEHINT_ID, THRESHOLD_ID)
VALUES (
           (SELECT ID FROM CLIMATEHINTS WHERE HINT_TEXT='Ventilate the room immediately by opening windows.'),
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER')
       );


-- =============================================================================
-- MEASUREMENTS  — explicit rows, ~4 per day across key dates
-- Covers: Jan 23 – Apr 22, 2026 (sampled at 00:00, 06:00, 12:00, 18:00)
-- Rooms: Eng Office A/B, HR Office A/B, Mgmt Office A, Sales Office A,
--        Eng Common Area
-- Values are hand-picked to realistically vary and occasionally breach thresholds.
-- =============================================================================

-- Helper macro (not used — all inserts are explicit below)
-- Format: (TIMESTAMP, value, 'METRIC', room_subquery, station_subquery)

-- -----------------------------------------------------------------------
-- ENG OFFICE A
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 20.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 06:00:00', 21.4, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 23.7, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 18:00:00', 22.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 00:00:00', 19.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 06:00:00', 21.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 12:00:00', 24.2, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 18:00:00', 22.9, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-15 10:00:00', 27.6, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-15 14:00:00', 28.4, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 00:00:00', 20.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 23.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-01 00:00:00', 21.2, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-01 12:00:00', 24.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 00:00:00', 21.9, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 25.3, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 52.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 06:00:00', 55.3, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 60.1, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 18:00:00', 57.4, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 12:00:00', 62.8, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-03-08 09:00:00', 66.4, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-03-08 15:00:00', 69.1, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-01 12:00:00', 58.7, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 61.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 06:00:00', 280.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 340.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 18:00:00', 310.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 12:00:00', 370.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 390.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 14:00:00', 431.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 18:00:00', 415.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 1011.5, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-02-05 00:00:00', 1012.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 00:00:00', 1010.3, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 00:00:00', 1013.1, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-A-S1'));


-- -----------------------------------------------------------------------
-- ENG OFFICE B
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 21.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 24.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-02-10 12:00:00', 25.9, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-03-20 12:00:00', 27.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-03-20 18:00:00', 26.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 25.4, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 58.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 64.5, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-02-10 12:00:00', 67.2, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-04-21 08:00:00', 72.3, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 70.8, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 295.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-02-10 12:00:00', 360.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 385.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 1010.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-03-10 00:00:00', 1011.5, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1')),
                                                                                        (TIMESTAMP '2026-04-22 00:00:00', 1012.2, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-B-S1'));


-- -----------------------------------------------------------------------
-- HR OFFICE A
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 19.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 22.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-02-15 12:00:00', 23.4, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 22.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 24.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 45.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 50.5, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-02-15 12:00:00', 54.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-04-23 06:00:00', 63.5, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-04-23 12:00:00', 61.2, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 265.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-01-30 13:00:00', 348.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-01-30 17:00:00', 362.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 290.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 310.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 1012.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 00:00:00', 1011.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 00:00:00', 1013.5, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-A-S1'));


-- -----------------------------------------------------------------------
-- HR OFFICE B  (temperature + humidity only)
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 20.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 22.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-02-20 14:00:00', 26.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-02-20 18:00:00', 27.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-03-15 11:00:00', 25.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-03-15 15:00:00', 26.9, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 24.3, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 49.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 54.5, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-02-20 12:00:00', 57.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 55.3, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='HR Office B'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='HR-B-S1'));


-- -----------------------------------------------------------------------
-- MGMT OFFICE A
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 21.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 22.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-02-15 12:00:00', 23.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-03-01 09:00:00', 24.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-03-01 12:00:00', 25.6, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 23.2, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 43.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 48.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 50.5, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 47.2, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 245.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 270.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 260.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 1013.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 00:00:00', 1012.5, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 00:00:00', 1014.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Mgmt-A-S1'));


-- -----------------------------------------------------------------------
-- SALES OFFICE A  (hot + humid, frequently breaches)
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 23.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 26.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-02-10 12:00:00', 27.4, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-03-15 12:00:00', 28.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 29.2, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 18:00:00', 28.7, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 60.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 68.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-02-10 12:00:00', 71.5, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 73.0, 'HUMIDITY', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 390.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-01-25 12:00:00', 512.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-02-28 13:00:00', 480.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-02-28 17:00:00', 498.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 430.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 1009.5, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-03-10 00:00:00', 1010.5, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1')),
                                                                                        (TIMESTAMP '2026-04-22 00:00:00', 1008.0, 'PRESSURE', (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Sales-A-S1'));


-- -----------------------------------------------------------------------
-- ENG COMMON AREA  (temperature + IAQ only)
-- -----------------------------------------------------------------------
INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 00:00:00', 19.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 21.0, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-02-15 12:00:00', 21.8, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 20.5, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 22.1, 'TEMPERATURE', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1'));

INSERT INTO MEASUREMENT (TIMESTAMP, MEASUREMENT, METRIC, ROOM_ID, SENSORSTATION_ID) VALUES
                                                                                        (TIMESTAMP '2026-01-23 06:00:00', 295.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-01-23 12:00:00', 370.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-02-15 12:00:00', 400.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-03-10 12:00:00', 340.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1')),
                                                                                        (TIMESTAMP '2026-04-22 12:00:00', 380.0, 'IAQ', (SELECT ID FROM ROOMS WHERE NAME='Eng Common Area'), (SELECT ID FROM SENSORSTATIONS WHERE NAME='Eng-Common-S1'));


-- =============================================================================
-- THRESHOLD VIOLATIONS
-- =============================================================================

-- Eng Office A — TEMPERATURE resolved (heat wave Feb 15)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-02-15 16:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'),
           TIMESTAMP '2026-02-15 11:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
           28.4, 'TEMPERATURE', 'RESOLVED'
       );

-- Eng Office A — HUMIDITY resolved (Mar 8)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-03-08 15:30:00',
           (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'),
           TIMESTAMP '2026-03-08 09:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER'),
           69.1, 'HUMIDITY', 'RESOLVED'
       );

-- Eng Office A — IAQ ACTIVE
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           NULL,
           (SELECT ID FROM ROOMS WHERE NAME='Eng Office A'),
           TIMESTAMP '2026-04-22 14:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
           431.0, 'IAQ', 'ACTIVE'
       );

-- Eng Office B — HUMIDITY ACTIVE
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           NULL,
           (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'),
           TIMESTAMP '2026-04-21 08:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER'),
           72.3, 'HUMIDITY', 'ACTIVE'
       );

-- Eng Office B — TEMPERATURE resolved (Mar 20)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-03-20 18:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='Eng Office B'),
           TIMESTAMP '2026-03-20 12:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Eng Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
           27.8, 'TEMPERATURE', 'RESOLVED'
       );

-- HR Office A — IAQ resolved (Jan 30)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-01-30 17:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='HR Office A'),
           TIMESTAMP '2026-01-30 13:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
           362.0, 'IAQ', 'RESOLVED'
       );

-- HR Office A — HUMIDITY ACTIVE
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           NULL,
           (SELECT ID FROM ROOMS WHERE NAME='HR Office A'),
           TIMESTAMP '2026-04-23 06:30:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office A') AND METRIC='HUMIDITY' AND THRESHOLD_TYPE='UPPER'),
           63.5, 'HUMIDITY', 'ACTIVE'
       );

-- HR Office B — TEMPERATURE resolved (Feb 20)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-02-20 19:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='HR Office B'),
           TIMESTAMP '2026-02-20 14:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
           27.1, 'TEMPERATURE', 'RESOLVED'
       );

-- HR Office B — TEMPERATURE resolved (Mar 15)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-03-15 16:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='HR Office B'),
           TIMESTAMP '2026-03-15 11:30:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='HR Office B') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
           26.9, 'TEMPERATURE', 'RESOLVED'
       );

-- Mgmt Office A — TEMPERATURE DISABLED
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-03-01 12:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A'),
           TIMESTAMP '2026-03-01 09:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Mgmt Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
           25.6, 'TEMPERATURE', 'DISABLED'
       );

-- Sales Office A — IAQ resolved (Jan 25)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-01-25 18:00:00',
           (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'),
           TIMESTAMP '2026-01-25 12:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
           512.0, 'IAQ', 'RESOLVED'
       );

-- Sales Office A — IAQ resolved (Feb 28)
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           TIMESTAMP '2026-02-28 17:30:00',
           (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'),
           TIMESTAMP '2026-02-28 13:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='IAQ' AND THRESHOLD_TYPE='UPPER'),
           498.0, 'IAQ', 'RESOLVED'
       );

-- Sales Office A — TEMPERATURE ACTIVE
INSERT INTO THRESHOLDVIOLATIONS (END_TIME, ROOM_ID, START_TIME, THRESHOLD_ID, "value", METRIC, VIOLATION_STATUS)
VALUES (
           NULL,
           (SELECT ID FROM ROOMS WHERE NAME='Sales Office A'),
           TIMESTAMP '2026-04-22 12:00:00',
           (SELECT ID FROM THRESHOLDS WHERE ROOM_ID=(SELECT ID FROM ROOMS WHERE NAME='Sales Office A') AND METRIC='TEMPERATURE' AND THRESHOLD_TYPE='UPPER'),
           29.2, 'TEMPERATURE', 'ACTIVE'
       );